### ISSUE TITLE
Set URL Dynamically from another service

### ISSUE THREAD

**Issue by growthclick** [troyanskiy/ng2-resource-rest#12]
Great library!  This might be more of a Readme or user issue as I couldn't figure it out - is there any way to dynamically set the URL (e.g. inject it from another service) rather than hard-coding it into the ResourceParams decorator?  Thanks in advance

**Comment by troyanskiy** [comment]
Thank you.
Could you please give some example how it should work? I will think about that.

**Comment by growthclick** [comment]
I'm migrating from NG1/Ionic 1 and would like to use different URL's between dev, test, and production environments. Assuming that Decorators do not allow DI of other services, maybe there could be an option to over-ride the constructor and call a "setURL" function to pass the target URL as in:   

export class AgentService extends Resource {
  constructor(public http: Http, private config: AppConfigService) {
	  super(http);
	  super.setURL(config.url());
  }	
}

In this example, the AppConfigService would return the URL of the server for this environment (e.g. localhost in dev and abc.com in production). I'm new to NG2 so if there's a better way I'd be interested to learn.  Thanks

**Comment by troyanskiy** [comment]
For now I see 2 ways:
1.
``` ts
@ResourceParams({
    // Url to api
    url: config.url(),
    // Api path
    path: '/agent/{id}'
})
export class AgentService extends Resource {}
```

2.
``` ts
@ResourceParams({
    // Api path
    path: '/agent/{id}'
})
export class AgentService extends Resource {

  constructor(@Inject(Http) protected http: Http, private config: AppConfigService) {}

  // and here overwrite getUrl method
  getUrl(): string {
    return this.config.url();
  }
}
```

I'm also new on NG2 ;) So I hope it will help you.
Let me know how it will work.

**Comment by growthclick** [comment]
Thanks @troyanskiy - getting back into this project and found the following approach works well: 

 getUrl(): string {
     return new AppConfigService().url();
  } 

I tried option 1 but had trouble with a decorator calling an instance method. I could have tried converting the method to static, but the above over-riding of getURL was a quicker fix, and didn't require a constructor. AppConfigService is really lightweight so creating a new instance is fine.  Thanks for the help!

**Comment by growthclick** [comment]
I've been using ng2-resource-rest for a day now and it's saving me hours - thanks! 

Just a quick add-on to my last comment: I ran into some issues in trying to pull in URL's and tokens from other NG2 services (typescript assignment errors). The approach that worked for me was to use a static class level variable (to get the token from another class), and to extend Resource into a new class. In case this might help anyone else, here is the example code:  

Snippet from UserService Class that provides a token after authenticating users: 

export class UserService {
    static lastToken = 'test123';  // this token gets updated as soon as the user logs in (e.g. UserService.lastToken = X). Making it static let me use it from the Ng2-resource-rest class 
 
Here is a simple subclass I created on Resource that sets the URL and headers:

import {Resource, ResourceParams} from "ng2-resource-rest";
import {Injectable} from "@angular/core";
import {RequestMethod} from "@angular/http";
import {Http} from "@angular/http";
import {AppConfig} from '../../config/app-config';
import {UserService} from '../user/user.service';

@Injectable()
@ResourceParams({})
export class GCResource extends Resource {
   
  getUrl(): string {
     return new AppConfig().url();
  }
  getHeaders(): any { 
    // Prepare headers with user authentication token if it exists
    var tokenUser = new UserService(this.http); 
    var authToken = UserService.lastToken; 
 
    var authHeaders:any; 
    authHeaders = {
            'Accept': 'application/json',
            'Content-Type': 'application/json'
    };
    if (authToken) { 
        var bearer = 'Bearer ' + authToken;
        authHeaders = {
            'Authorization': bearer,
            'Accept': 'application/json',
            'Content-Type': 'application/json'
        };
    }
    return authHeaders;
  }
} 

With the above setup, each new resource class is very minimalist:  

import {ResourceParams} from "ng2-resource-rest"; 
import {GCResource} from "../../services/gc-resource/gc-resource"; // API Helper library 
import {Injectable} from "@angular/core";
 
@Injectable()

@ResourceParams({
  path: '/admin/org/users/{id}'
})
 // GCResource extends NG2-Resource-rest with URL and user token 
export class UserAdminService extends GCResource {  

}
 
Still getting the handle of Typescript and NG2... hopefully this example helps someone.

**Comment by troyanskiy** [comment]
Thanks a lot for your example...
Since `GCResource` is kink of base resource class I would recommend you to add `add2Provides`: false to `GCResource` so it will not make it as final global service.
So your `GCResource` base class should looks like
``` ts
@ResourceParams({
    add2Provides: false
})
export class GCResource extends Resource {

    getUrl(): string {
        return new AppConfig().url();
    }
    getHeaders(): any { 
        // Prepare headers with user authentication token if it exists
        var tokenUser = new UserService(this.http); 
        var authToken = UserService.lastToken;

        var authHeaders:any;
        authHeaders = {
            'Accept': 'application/json',
            'Content-Type': 'application/json'
        };
        if (authToken) { 
            var bearer = 'Bearer ' + authToken;
            // just add headers instead of recreating an object
            // authHeaders = {
            //    'Authorization': bearer,
            //    'Accept': 'application/json',
            //    'Content-Type': 'application/json'
            //};
            authHeaders['Authorization'] = bearer;
        }
        return authHeaders;
    }
}


```

**Comment by growthclick** [comment]
Good tip!  I see that will prevent GCResource from being added to RESOURCE_PROVIDERS.  Thanks

**Comment by radumardale** [comment]
Great module!
You should include an GCResource example in the README. It is really useful.
Thank you.

**Comment by troyanskiy** [comment]
@radumardale Thank you!
I will add it later!
Thanks a lot.

**Comment by troyanskiy** [comment]
New version has been released with changing url (not only) methods.
Please check README.
Thanks a lot.
