### ISSUE TITLE
ng2 rc1 :/node_modules/ng2-resource-rest/ 403 (Forbidden)  

### ISSUE THREAD

**Issue by iloveyo123u1** [troyanskiy/ng2-resource-rest#13]

**Comment by iloveyo123u1** [comment]
i fix it:

//systemjs.config.js
changge
 'ng2-resource-rest':        { defaultExtension: 'js' },

to
 'ng2-resource-rest':        { main: 'index.js',defaultExtension: 'js' },

**Comment by troyanskiy** [comment]
Thanks.
