### ISSUE TITLE
login error, submit data error

### ISSUE THREAD

**Issue by iloveyo123u1** [troyanskiy/ng2-resource-rest#16]
servers i used  http://www.django-rest-framework.org/
the app login page demo in there` http://restframework.herokuapp.com/api-auth/login/?next=/`

i want use `ng2-resource-rest`  login that

but, ng2-resource-rest submit data have question

i capture Chrome login data：
submit data is：`csrfmiddlewaretoken=G71nGgFwhUyguxhdNz8c6DdWLHDKKr6K&username=111111111&password=112222222222222&next=%2F&submit=Log+in`

-----------------------------------------------------

i use ng2-resource-rest：
code ：

```
 this.Res.login("csrfmiddlewaretoken=kgEviC68d6OAB23v5fZlu0e1GO5oig7c&next=&username=111111&password=222222&submit=Log+inName")
                .$observable
                .subscribe(
                  res => console.log(res),
                   err => console.log('Err', err)
               );
```

i capture Chrome login data：
`"csrfmiddlewaretoken=kgEviC68d6OAB23v5fZlu0e1GO5oig7c&next=&username=111111&password=222222&submit=Log+inName"`

**have  quotation marks**

--------------------------------------------------
then i change i code：
```
      this.Res.login({username: '111111', password: '222222',csrfmiddlewaretoken:'kgEviC68d6OAB23v5fZlu0e1GO5oig7c',next:'/',submit:'Log+in'})
                .$observable
            .subscribe(
                res => console.log(res),
                err => console.log('Err', err)
            );
```
i capture Chrome login data：
`{"username":"111111","password":"222222","csrfmiddlewaretoken":"kgEviC68d6OAB23v5fZlu0e1GO5oig7c","next":"/","submit":"Log+in"}`

**have {}**

------------------------------
so ,login error

would you help me ?

**Comment by troyanskiy** [comment]
That is normal.
Your server does not expect to receive JSON body. It expect to receive application/x-www-form-urlencoded (regular form) data.
For now the library sends only JSONs.

**Comment by gasparherrera** [comment]
use JWT for this
