### ISSUE TITLE
Type Script errors during preprocessing

### ISSUE THREAD

**Issue by bozhidarc** [troyanskiy/ng2-resource-rest#18]
Hi,

I'm using @mgechev angular2-seed and I decided to add your ng2-resource-rest component but, on the build process I'm getting the errors I post bellow.
If you need more information about my environment just say what to give you.

```
node_modules/ng2-resource-rest/index.ts(296,27): error TS2359: The right-hand side of an 'instanceof' expression must be of type 'any' or of a type assignable to the 'Function' interface type.
node_modules/ng2-resource-rest/index.ts(349,39): error TS2339: Property 'publish' does not exist on type 'Observable<any>'.
```

**Comment by troyanskiy** [comment]
I'have made some quick fixes.
Could you please update the lib and test it for me?
Thank you!

**Comment by bozhidarc** [comment]
Thanks, it builds now but I have another issue. It's about http property in ResourceParams, but I can create separate issue for that.

**Comment by troyanskiy** [comment]
Cool.
Yes, could you please create other issue.
Thank you.
My bad is that I have developed the lib quickly and did not use it much for now.
