### ISSUE TITLE
A traling slash "/" after a not mandatory option is removed

### ISSUE THREAD

**Issue by bozhidarc** [troyanskiy/ng2-resource-rest#20]
If for example I have the following url '/users/{id}' and the the id is null the final url will look line '/users/' which leads to a redirection to '/users' with some APIs, but the redirections are not allowed with CORS requests and leads to following error

`XMLHttpRequest cannot load http://example.com/users/. The request was redirected to ' http://example.com/users', which is disallowed for cross-origin requests that require preflight.`

**Comment by bozhidarc** [comment]
From what I saw you are replacing the parameter placeholders with empty string and after that you are splitting the final url by '//'. 
I think it will be cleaner if you are replacing not only **{param}** but  "/" with **{param}** which will save you all the slicing and joining and will fix the problem with the last slash :)

**Comment by troyanskiy** [comment]
Please update the library.
I have added parameter to decorators `removeTrailingSlash` which is `true` by default.
