### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://127.0.0.1' is therefore not allowed access.

### ISSUE THREAD

**Issue by iloveyo123u1** [troyanskiy/ng2-resource-rest#21]
res file

```
import {Resource, ResourceParams} from "ng2-resource-rest";

import {Injectable} from "@angular/core";


// Make it Injectable
@Injectable()
// Decorate the your resource class
@ResourceParams({
  // Url to api
  url: 'https://query.yahooapis.com',
  headers:{
    // "X-CSRFToken":csrftoken,
    'Access-Control-Allow-Origin' :'*',
    'Access-Control-Allow-Methods':'POST, GET, OPTIONS',
    'Accept': 'application/json',
    'Content-Type': 'application/json'
  },
  // Api path
  path: '/v1/public/yql'
})
export class YqlRes extends Resource {

}

```

ts code：

```
 getInfo(){
   let tsql='select * from json  where url="http://jsonplaceholder.typicode.com/posts"';
   this.yqlRes.get({q:tsql});

 }
```

then ' i got an error

`XMLHttpRequest cannot load https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20json%20%20where%20url%3D%22http%3A%2F%2Fjsonplaceholder.typicode.com%2Fposts%22&format=json&diagnostics=true&callback=. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://127.0.0.1' is therefore not allowed access.`

could you help me?

thank you very much

**Comment by troyanskiy** [comment]
That kind of header should be send by server.
Please read here about that https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

**Comment by iloveyo123u1** [comment]
thank you
