### ISSUE TITLE
Typescript Error

### ISSUE THREAD

**Issue by georgebatalinski** [troyanskiy/ng2-resource-rest#22]
**I am getting this error**
```
error TS2320: Interface 'ArrayResourceResult<T>' cannot simultaneously extend types 'ResourceResult' and 'T[]'.
  Named property '$resolved' of types 'ResourceResult' and 'T[]' are not identical.
```
[Reasoning](https://github.com/Microsoft/TypeScript/issues/3598)

**index.ts -pointing to this line** 
```
export interface ArrayResourceResult<T> extends ResourceResult, Array<T> {}
```

**My setup**
```
 tsc -v
Version 1.8.10
```

**Comment by troyanskiy** [comment]
Hello @georgebatalinski 
Sorry for long answer.
I have released new version 1.0.1 with broken changes.
Try to use it.
Thanks a lot.
