### ISSUE TITLE
Angular RC5 trouble

### ISSUE THREAD

**Issue by anfluff** [troyanskiy/ng2-resource-rest#23]
Hello!
On RC4 everything works perfect, but now i've just moved to RC5 and got problems.

I have structure like this:

```
client
|-app
    |- +question
        |-question.module.ts
        |-question.component.ts

|-shared
    |-shared.module.ts
        |-api
            |-resources
            	|-question.res.ts
|-app.module.ts
```

I've declared my **QuestionResource** in **SharedModule**: 
```
export class SharedModule {
    static forRoot(): ModuleWithProviders {
        return {
            ngModule: SharedModule,
            providers: [
                QuestionRes
            ]
        };
    }
}
```

In **QuestionComponent** i have:
```
ngOnInit() {
    this._questionRes.query()
}
```

And when page loads i recieve error:
```
TypeError: Cannot read property 'request' of undefined at eval (http://localhost:5555/node_modules/ng2-resource-rest/index.js:305:44)
```

As i understood, angular missing **Http** in **Resource** constructor.
According to this i've added to my **QuestionResource** own constructor to pass **Http** to **Resouce** constructor (_just for test_).
```
constructor(@Inject(Http) protected http: Http) {
        super.constructor(this.http);
    }
```

After this, request loaded as it used to. But i've got another errors in **Resource**...

---
 
Help me please. Have no opinion what to fix in my code.

**Comment by troyanskiy** [comment]
@anfluff thank you for using my module.
I did a little refactored it and could you please try that:
``` ts
export class SharedModule {
    static forRoot(): ModuleWithProviders {
        return {
            ngModule: SharedModule,
            providers: [
                ResourceProviders.main()
            ]
        };
    }
}
```

If it will not help you, could you please show me your full `question.res.ts` file.

**Comment by anfluff** [comment]
Wow. It works perfect, thank you!
But i found another errors.

If i use construction like this:
```
this._questionRes.query().$observable.subscribe(questions => this.questions = questions);
```
Everything works fine.
But when i change it to:
```
this.questions = this._questionRes.query();
```
I receive errors:
```
TypeError: Cannot read property 'next' of null at eval (http://localhost:5555/node_modules/ng2-resource-rest/index.js:336:35)
```

**Comment by troyanskiy** [comment]
@anfluff Yes... Indeed there is a bug.
I will fix that.
Thank you.

**Comment by troyanskiy** [comment]
@anfluff the bug is fixed. Please update the version of the module.

**Comment by anfluff** [comment]
Nice! Thank you :smiley:

**Comment by anfluff** [comment]
Hello!
Once again i've got a trouble.
(I'm using same app structure as before)

When i moved to ng2-resource-rest 1.2.0 i've added **ResourceModule.forRoot()** to my *AppModule* and removed **ResourceProviders.main()** from  **SharedModule**. Next i changed all my resources to extend from ResourceCRUD.

Now i receive error about injection:
 `Can't resolve all parameters for QuestionComponent: (ActivatedRoute, ?, ErrorService)`
? = QuestionRes.

Should i register my resources as providers in **SharedModule** somehow?
If I just list them in providers array, error does not disappear.

**Comment by troyanskiy** [comment]
Hello @anfluff 
Could you please share your app module and questions sources? I can't answer your question without seeng your code.
Thanks.

**Comment by anfluff** [comment]
**AppModule**:

``` typescript
import { NgModule }      from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { APP_BASE_HREF } from '@angular/common';
import { RouterModule }  from '@angular/router';
import { HttpModule }    from '@angular/http';
import { FormsModule }   from '@angular/forms';

import { ResourceModule } from "ng2-resource-rest";

import { AppComponent } from './app.component';
import { routes } from './app.routes';

import { SharedModule } from './shared/shared.module';
import { HomeModule } from './+home/home.module';

@NgModule({
    imports: [
        BrowserModule,
        HttpModule,
        FormsModule,

        RouterModule.forRoot(routes),
        ResourceModule.forRoot(),
        SharedModule.forRoot(),

        HomeModule, 
	... // other modules
    ],
    declarations: [ AppComponent ],
    providers: [{
        provide: APP_BASE_HREF,
        useValue: '<%= APP_BASE %>'
    }],
    bootstrap: [AppComponent]

})

export class AppModule { }

```

**QuestionRes**:

``` typescript
import {ResourceCRUD, ResourceParams} from "ng2-resource-rest";
import {Injectable} from "@angular/core";
import { Observable }     from 'rxjs/Observable';
import { Config } from './../../config/env.config';

import { handleResponse } from './_response-handle';
import { Question } from './../index';

@Injectable()
@ResourceParams({
    url: Config.API,
    headers: Config.Headers,
    path: '/questions/{id}'
})
export class QuestionRes extends ResourceCRUD {
    responseInterceptor (observable:Observable<any>):Observable<any> {
        return handleResponse(observable, Question)
    }
}
```

Usage: 

``` typescript
this._questionRes.query().$observable.subscribe(
        questions => this.questions = questions,
        error => this._errorService.showError('Questions query error', error)
);
```

Thats all or u need some more files?

**Comment by anfluff** [comment]
It does't help :C
My **SharedModule** is:

``` typescript
import { NgModule, ModuleWithProviders } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { HttpModule } from "@angular/http";
import { ResourceModule } from "ng2-resource-rest";

import { ToolbarComponent } from './toolbar/index';
import { NavbarComponent } from './navbar/index';
import { FooterComponent } from './footer/index';
import { AuthService, AuthGuard } from './auth/index';

@NgModule({
    imports: [CommonModule, RouterModule, HttpModule],
    declarations: [
        ToolbarComponent,
        NavbarComponent,
        FooterComponent
    ],
    exports: [
        CommonModule,
        FormsModule,
        RouterModule,

        ResourceModule.forRoot(), // does'nt fix error :(

        NavbarComponent,
        ToolbarComponent,
        FooterComponent
    ]
})
export class SharedModule {
    static forRoot(): ModuleWithProviders {
        return {
            ngModule: SharedModule,
            providers: [
                AuthService,
                AuthGuard
            ]
        };
    }
}
```

**Comment by troyanskiy** [comment]
Honestly I have no idea.
Can you share all your code on github or send me by email roma at redbox.by?

**Comment by anfluff** [comment]
Im using this angular 2 seed - https://github.com/mgechev/angular2-seed
Ive tryed to install my ng2-resource on clean seed and it works.
So error somewhere in my code.
And i think it in ResourceCrud declaration. I forgot to add stuff in <> brackets 
``` typescript
export class QuestionRes extends ResourceCRUD
```
vs
``` typescript
export class NewRes extends ResourceCRUD<IQueryInput, INewsShort, INews> {}
```

So thank you a lot for help! 
I will try to fix it myselft.

**Comment by pydrive** [comment]
Hi, I'm am also getting the same error with 1.5.0 version. 
Boilerplate I've been using: https://github.com/AngularClass/angular2-webpack-starter
`
error_handler.js:46EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'request' of undefinedErrorHandler.handleError @ error_handler.js:46next @ application_ref.js:298schedulerFn @ async.js:89SafeSubscriber.__tryOrUnsub @ Subscriber.js:223SafeSubscriber.next @ Subscriber.js:172Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:81onError @ ng_zone.js:123onHandleError @ ng_zone_impl.js:62ZoneDelegate.handleError @ zone.js:336Zone.runGuarded @ zone.js:242_loop_1 @ zone.js:508drainMicroTaskQueue @ zone.js:515ZoneTask.invoke @ zone.js:437
`

And now this solution works for me:
```javascript
constructor(http: Http, injector: Injector){
    super(http, injector)
  }
```
