### ISSUE TITLE
error TS6059 index.ts is not under 'rootDir'

### ISSUE THREAD

**Issue by almothafar** [troyanskiy/ng2-resource-rest#25]
Hi, 

I'm working in NativeScript with Angular2 and Typescript project, the problem that when i'm trying to build project I get the following error:

`error TS6059: File 'D:/XYZ/Groceries/node_modules/ng2-resource-rest/index.ts' is not under 'rootDir' 'D:/XYZ/Groceries/app'. 'rootDir' is expected to contain all source files.`

you can see the tsconfig.json and whole project here : 
https://github.com/NativeScript/sample-Groceries

I just installed `ng2-resource-rest` and I'm trying to use it.

Config: 
```
{
    "compilerOptions": {
        "outDir": "app",
        "rootDir": "app",
        "module": "commonjs",
        "target": "es5",
        "inlineSourceMap": true,
        "experimentalDecorators": true,
        "removeComments": false,
        "emitDecoratorMetadata": true,
        "noEmitOnError": true
    },
    "exclude": [
        "node_modules",
        "platforms"
    ]
}
```

**Comment by troyanskiy** [comment]
Hello.
Please [check here](http://stackoverflow.com/questions/35648347/importing-ng2-bootstrap-changes-my-tsc-output-directory-structure/35878902#35878902) the solution.
Let me know how it will work for you.

**Comment by almothafar** [comment]
@troyanskiy thank you for reply, the problem that I'm using nativescript now, where to place code? you can simply clone the project in question and then install `ng2-resource-rest`  

So the solution provided could be from your side? you have to provide d.ts and js not the source, see this [nativescript-angular](https://github.com/NativeScript/nativescript-angular)

**Comment by almothafar** [comment]
In another dependencies, there is no `tsconfig.ts`, and no `*.ts`, no `*.map`, only `*.d.ts` and `*.js`.

**Comment by almothafar** [comment]
Issue fixed, thanks.

**Comment by troyanskiy** [comment]
Thanks a lot!
