### ISSUE TITLE
error index.d.ts(1,1): error TS6053 ng2-resource-rest/node_modules/@types/es6-shim/index.d.ts' not found

### ISSUE THREAD

**Issue by almothafar** [troyanskiy/ng2-resource-rest#27]
Issue #25 fixed, but now there is a reference from your `devDependencies` inside index.d.ts that making this issue

i removed it in my local file the project worked.

**Comment by almothafar** [comment]
Tested again, seems its solved now, thanks.

**Comment by troyanskiy** [comment]
Thanks a lot!
