### ISSUE TITLE
Feature request: ability to define a default URL globally

### ISSUE THREAD

**Issue by smnbbrv** [troyanskiy/ng2-resource-rest#30]
Can we specify the url ResourceParamsBase property in a global way for the whole application (e.g. in a bootstrap file)? Maybe it is not that useful for every project but still would be nice to have

**Comment by troyanskiy** [comment]
For that case usually I'm creating the `BaseResource` and all other resources are extended by BaseResource

**Comment by magnitronus** [comment]
common params:

`import {ResourceParams, ResourceParamsBase} from 'ng2-resource-rest';
import {Headers} from '@angular/http';

export function CommonResourceParams(params: ResourceParamsBase) {

	let token = window.localStorage.getItem('auth_token');
	params.headers = new Headers();

	params.headers.append('Content-Type', 'application/json');
	params.headers.append('Authorization', `Token ${token}`);

	params.url = `${process.env.API_BASE_URL}/api`;
	params.removeTrailingSlash = false;

	return ResourceParams(params);
}`

resource:

`@Injectable()
@CommonResourceParams({
    path: '/users/{id}/'
})
export class UserResource extends Resource {

}`

**Comment by smnbbrv** [comment]
@magnitronus awesome, thanks!
