### ISSUE TITLE
'data' parameter persisting between requests

### ISSUE THREAD

**Issue by spongessuck** [troyanskiy/ng2-resource-rest#32]
I have two components using the same Resource subclass, but they're making requests with different parameters. The trouble is that parameters set using one persist when they're not included in the other. I've even tried adding the resource to the components' `providers` array so that each one gets its own instance, but that doesn't seem to work.

For example if I make a request in one component:

    constructor(private resource: ResourceSubclass) {}
    ...
    this.items = this.resource.query({ param1: 'foo' });

The query string will be `?param1=foo`, which is expected.

Then, if I switch routes and another component makes a request using the same Resource type:

    constructor(private resource: ResourceSubclass) {}
    ...
    this.items = this.resource.query({ param2: 'bar' });

The query string will be `?param2=bar&param1=foo`, which is unexpected. Each request should have its own parameters created based on the data passed in through the method and the `data` parameter in the ResourceParams decorator. Parameters shouldn't persist between calls unless they're in the decorator.

I tried to dig through the source but I can't find what's causing this behavior.

**Comment by troyanskiy** [comment]
Hello @spongessuck 
That's really strange.
Could you please share the ResourceSubclass code and related to it classes?
Thanks

**Comment by spongessuck** [comment]
You should find the relevant files here:

https://gist.github.com/spongessuck/8d14e309da47cf45f7d6ceae1aecd111

**Comment by troyanskiy** [comment]
This is weird.
I have never had that case.
Is it possible to debug it somewhere live.
btw this week I will update to version 1 and there is breaking changes.
So maybe better to wait new version?

**Comment by spongessuck** [comment]
Sure, I can work around the issue until then.

**Comment by troyanskiy** [comment]
Hello @spongessuck 
I have released new version. Please check if it resolves you bug.
Thanks.

**Comment by spongessuck** [comment]
I'll try it. Is the only change from 0.x to 1.x that you use the module?

**Comment by troyanskiy** [comment]
not only module change.
please check readme

**Comment by spongessuck** [comment]
I'm all updated to v1.0.1 and this problem persists.

**Comment by troyanskiy** [comment]
I think I found the bug.
I did not have time to test, but I've bumped update 1.0.2
Could you please try it?
Thanks.

**Comment by spongessuck** [comment]
Doesn't look like it's fixed, sorry.

**Comment by troyanskiy** [comment]
Do you have somewhere access to dev (server)?
Or can you share your project?
You can send me by email (roma@redbox.by), if you can't share it on public.

**Comment by spongessuck** [comment]
OK, I think webpack wasn't re-bundling the new version; I put the source ResourceAction.ts in my node_modules package to try and debug, and after I started adding some console.logs, I couldn't recreate the problem anymore. I thought maybe it had to do with the transpiling process and got rid of the .ts file, but then I still couldn't recreate it.

So I believe your last update probably fixed it. Thanks so much for your time on this!
