### ISSUE TITLE
v1.0.1 Can't override ResourceCRUD ResourceActions

### ISSUE THREAD

**Issue by spongessuck** [troyanskiy/ng2-resource-rest#33]
I'm having trouble overriding actions from the ResourceCRUD class.

For example, in one class I'm doing a sort on the results of query() before it gets passed to the caller. I can't figure out how I would do that using a ResourceCRUD subclass without wrapping the whole thing in a service.

**Comment by troyanskiy** [comment]
Hello @spongessuck 

You can define custom responseInterceptor for the method

```ts
import { ResourceCRUD, ResourceParams, ResourceMethod, ResourceAction } from 'ng2-resource-rest';
import {Observable} from 'rxjs';

@ResourceParams({})
export class testRes extends ResourceCRUD<any, any, any> {

  @ResourceAction({
    responseInterceptor: function (observable:Observable<any>):Observable<any> {
      return observable
        .map(res => {
          if (!res._body) {
            return null;
          }

          return res
            .json()
            .sort((a:any, b: any) => a.value - b.value);
        });
    }
  })
  query: ResourceMethod<any, any[]>;

}
```

**Comment by spongessuck** [comment]
Thanks, I was working on this when I saw your answer. I'm having some other trouble with it, but this answers my question so I'm closing.
