### ISSUE TITLE
rc6 issue

### ISSUE THREAD

**Issue by ssi-hu-tasi-norbert** [troyanskiy/ng2-resource-rest#34]
I'd like to use your module in my app. It seems to be even better than the earlier versions, but I've got stuck at the importing phrase.
Error: Invalid provider for the NgModule 'ResourceModule' - only instances of Provider and Type are allowed, got: [?undefined?]

Could you help me?

Thank you in advance.

**Comment by troyanskiy** [comment]
Hello.
Could you please show me your module file and resource classes?

**Comment by ssi-hu-tasi-norbert** [comment]
I've just put the ResourceModule.forRoot() into the imports phrase, just like you in the readme. I don't have any resource yet.

**Comment by ssi-hu-tasi-norbert** [comment]
Maybe that's the point. I've tried to import into my shared.module the ResourceProviders.get(), just like you and I got the same error. The providers['__mainProviders'] is undefined I guess.

**Comment by troyanskiy** [comment]
Yes... Create resources and all should be fine.

**Comment by ssi-hu-tasi-norbert** [comment]
I've tried before. Maybe I've missed something. I'd like to create lazy loading module, that's why I had no resources, I guess. This case I should use ResourceModule.forChild('something'). Should I give the name for child resource with 'providersSubSet' ResourceParam?

**Comment by troyanskiy** [comment]
Yes, you need to decorate your resource
``` ts
@ResourceParam({
  providersSubSet: 'something'
})
export class YourResource extends Resource {
......
```

**Comment by ssi-hu-tasi-norbert** [comment]
Thank you for your quick replies and the fix. It works with lazy loading too and without resources even if it's meaningless, I know.
I know it is off topic, but : can you extend Resource without constructor in which the http passed to the parent? Because for me without it :_this.http is undefined (ResourceAction.js)

`@ResourceParams({
  path: '/api/blog/{id}',
  providersSubSet: 'blog'
})
export class BlogService extends Resource {

   **constructor(protected http: Http) {
      super(http);
    }**

    @ResourceAction({
        method: RequestMethod.Get
    })
    query: ResourceMethod<Search, Blog[]>;

}`

**Comment by troyanskiy** [comment]
Well...
Normally it should work without constructor. I'm using the library without it.
```ts
@Injectable()
@ResourceParams({
  path: '/api/blog/{id}',
  providersSubSet: 'blog'
})
export class BlogService extends Resource {
    @ResourceAction({
        //method: RequestMethod.Get - not necessary to define get request. It's default
       isArray: true // isArray parameter should be true if you expects to receive an array
       //  I can see that from your out type Blog[]
    })
    query: ResourceMethod<Search, Blog[]>;
}
```

**Comment by ssi-hu-tasi-norbert** [comment]
Maybe some setting issue. I can live with that till I find some time to look deeper.
Thank you for your module and time.
This issue can be closed.
Have a nice day!

**Comment by troyanskiy** [comment]
Thanks.
Have a great day!

**Comment by GregJPreece** [comment]
Just wanted to add to this thread that I've also encountered the "this._http is undefined" error in my app, and was able to fix it in the same way:

```typescript
@Injectable()
@ResourceParams({
    url : 'http://localhost:9000/content'
})
export class ContentItemModel extends ResourceCRUD<IContentItemQuery, IContentItemShort, IContentItem> {
    constructor(protected http: Http, protected injector: Injector) {
        super(http, injector);
    }
}
```

I'm wondering if it has to do with the package manager/loader used. I'm using JSPM. @ssi-hu-tasi-norbert How about you?

**Comment by ssi-hu-tasi-norbert** [comment]
I build with webpack and I have to use it the same. afaik it is the way to use extending, @troyanskiy is a magician. :)

**Comment by troyanskiy** [comment]
@ssi-hu-tasi-norbert thank you!
