### ISSUE TITLE
URL with multiple ids

### ISSUE THREAD

**Issue by CyrilleGuimezanes** [troyanskiy/ng2-resource-rest#36]
Hello!

In my application I have, sometimes, complexe URL like:

> /api/v1/cars/{id}/pieces/{id2}/detail/{id3}

But when I call .get() or .remove() methods I get some warnings like:

> Argument of type '{ id: number; id2: number; id3: number; }' is not assignable to parameter of type '{ id: any; }'.

If we take a look at the ResourceCRUD definition, it's understable:

```
get: ResourceMethod<{
        id: any;
    }, TFull>;

remove: ResourceMethod<{
        id: any;
    }, any>;

```
It's limited to one id in the URL.

Unless it's on the REST strict definition, maybe this param could be less limited. Am I right?

Regards,

**Comment by troyanskiy** [comment]
Hello.
Yes. Provided predefined CRUD resource is limited to receive only one path parameter.
I have just created `ResourceCRUDBase<TQuery, TKeys, TShort, TFull>` resource.
I think it will fit your need.
Please update to 1.2.0

**Comment by troyanskiy** [comment]
Example

```ts
export interface IQuery {
  name: string;
}
export interface IKeys {
  id1: string;
  id2: string;
  id3: string;
}
export interface IDetailShort extends IKeys {
  ref: string;
  name: string;
}
export interface IDetail extends IDetailShort {
  description: string;
}

@ResourceParams({
  path: '/api/v1/cars/{id}/pieces/{id2}/detail/{id3}'
})
export class MyResource extends ResourceCRUDBase<IQuery, IKeys, IDetailShort, IDetail> {}
```

**Comment by CyrilleGuimezanes** [comment]
Great! Confirmed, fixed :)
