### ISSUE TITLE
Unexpected value 'AppComponent' declared by the module 'AppModule'

### ISSUE THREAD

**Issue by nuclearkote** [troyanskiy/ng2-resource-rest#39]
When I add ResourceModule.forRoot() to AppModule-imports I get that error.

import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { ResourceModule } from 'ng2-resource-rest';

import { AppComponent } from './app.component';
import { APP_ROUTING } from './app.routing';

@NgModule({
    declarations: [
        AppComponent
    ],
    imports: [
        BrowserModule,
        ResourceModule.forRoot(),
        APP_ROUTING
    ],
    providers: [],
    bootstrap: [AppComponent]
})
export class AppModule {
}

**Comment by magnitronus** [comment]
It seems like effect of circular dependencies... @nuclearkote What angular version do you use?

**Comment by nuclearkote** [comment]
@magnitronus 
  "dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/router": "3.0.0",
    "core-js": "^2.4.1",
    "ng2-resource-rest": "^1.3.2",
    "rxjs": "5.0.0-beta.12",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.6.23"
  }

**Comment by nuclearkote** [comment]
I updated ng2-resourse-test and now it works.

**Comment by magnitronus** [comment]
Nice.
