### ISSUE TITLE
good job  thank you

### ISSUE THREAD

**Issue by iloveyo123u1** [troyanskiy/ng2-resource-rest#4]
good job  thank you

**Comment by troyanskiy** [comment]
thanks! :)

**Comment by troyanskiy** [comment]
Let me know if you will need something extra ;)

**Comment by iloveyo123u1** [comment]
Thank you for your reply，Server I use is Django-rest-framework http://www.django-rest-framework.org/
in angular1 https://docs.angularjs.org/api/ngResource very good，
but ngResource not support angular2
Can you transplant it ？

thank you once again

**Comment by troyanskiy** [comment]
There is no resource in angular 2, thats why I developed that module.
Since angular 2 for http is using rxjs you need to subscribe to receive the data.
So in angular 1 it's something like that
``` javascript
var news = NewsResource.query();
```
For angular 2 it should be like that
``` javascript
let news:any;
NewsResource.query().subscribe( responceData => { news = responceData } );
```

I'm thinking to implement something like that, which should work like angular1
``` javascript
var news = NewsResource.query().$ng1()
```

**Comment by iloveyo123u1** [comment]
thank you

**Comment by troyanskiy** [comment]
I have released new version on the module.
There is breaking functionality but it works now like in angular1.
All methods returns an object or an array with `$resolved` property and `$observable` object (in angular1 it was `$promise`). But if you need a promise, you can call `$observable.toPromise()`.
So you can do something like that.
``` javascript
var news = NewsResource.query();
```

**Comment by troyanskiy** [comment]
I bit later I will update the documentation

**Comment by iloveyo123u1** [comment]
thank you,please push  v.0.2.1 to npm

**Comment by troyanskiy** [comment]
It's pushed.
https://www.npmjs.com/package/ng2-resource-rest

**Comment by iloveyo123u1** [comment]
thank you , can you update the documentation  now ? because I'm trying to use it now,

**Comment by troyanskiy** [comment]
the documentation has been updated

**Comment by iloveyo123u1** [comment]
thank you very much
