### ISSUE TITLE
Unexpected token export

### ISSUE THREAD

**Issue by smnbbrv** [troyanskiy/ng2-resource-rest#40]
Actually subj. `Uncaught SyntaxError: Unexpected token export` error happens when I use the latest version of the library. If I use `~1.3.0` it does not happen.

What kind of additional input would you need to fix the issue?

**Comment by troyanskiy** [comment]
Checking that.
You can use 1.4.1 for now. I will let you know when the bug will be fixed

**Comment by troyanskiy** [comment]
@smnbbrv please try 1.4.5

**Comment by smnbbrv** [comment]
@troyanskiy works fine, thank you Sir!
