### ISSUE TITLE
Angular 2.0.0 Support

### ISSUE THREAD

**Issue by growthclick** [troyanskiy/ng2-resource-rest#41]
Ionic just released Ionic 2 RC with Angular 2.0.0 underneath. From the Angular change log (https://github.com/angular/angular/blob/master/CHANGELOG.md), it doesn't look like there were many breaking changes from Angular 2 RC 6 to 2.0.0, so I'm getting ready to try updating. Do you know if ng2-resource-rest works with Angular 2.0 Final?  I can try and share my findings if that would be helpful. Thanks

**Comment by troyanskiy** [comment]
Yes. It works. I have updated to 2.0.1

**Comment by growthclick** [comment]
Awesome! This library has been incredibly useful. Thanks again
