### ISSUE TITLE
@types

### ISSUE THREAD

**Issue by vlados** [troyanskiy/ng2-resource-rest#42]
When the project will be implemented with typings so it can be imported in ionic2 project?
More info about the problem: http://stackoverflow.com/questions/39821067/ionic2-and-ng2-resource-rest-missing-typings

**Comment by vlados** [comment]
Also from angula2 docs - https://github.com/angular/angular-cli#3rd-party-library-installation
Output:

> Vladislavs-MacBook-Pro:ionic-rest vlado$ npm install @types/ng2-resource-rest --save-dev
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.7.0/bin/node" "/usr/local/bin/npm" "install" "@types/ng2-resource-rest" "--save-dev"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.7
npm ERR! code E404
npm ERR! 404 Not found : @types/ng2-resource-rest
npm ERR! 404 
npm ERR! 404  '@types/ng2-resource-rest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm ERR! Please include the following file with any support request:
npm ERR!     /Users/vlado/code/tests/ionic-rest/npm-debug.log
Vladislavs-MacBook-Pro:ionic-rest vlado$

**Comment by troyanskiy** [comment]
Thanks for the Issue...
I'll check that ASAP because I'm going to use it with Ionic2 also shortly.

**Comment by vlados** [comment]
If I can help just tell me

**Comment by troyanskiy** [comment]
Please try update 1.4.7. Should be fine now.

**Comment by vlados** [comment]
After update:
> [00:21:33]  src/app/apiservice.ts(2,72): error TS2307: Cannot find module 'ng2-resource-rest'.
[00:21:33]  src/app/app.module.ts(6,32): error TS2307: Cannot find module 'ng2-resource-rest'.
[00:21:33]  typescript compiler ready in 3.65 s
[00:21:33]  bundle dev started ...
[00:21:39]  Error: Module /Users/vlado/code/tests/ionic-rest/node_modules/ng2-resource-rest/dist/index.js does not export ResourceMethod (imported by /Users/vlado/code/tests/ionic-rest/.tmp/app/apiservice.js)

Also, didn't I need to install it by:
`npm install --save @types/ng2-resource-rest`

**Comment by vlados** [comment]
Why you moved everything to dist folder? Now to make it work I need to have
`import {Resource, ResourceParams, ResourceAction, ResourceMethod} from 'ng2-resource-rest/dist';`

**Comment by troyanskiy** [comment]
@vlados I moved it by mistake... Please update to 1.4.9.
And, unfortunately I did not have time to check the issue with ionic deeper, previous quick fix was buggy so I had to unpublish the version.

**Comment by vlados** [comment]
I have the same problem with 1.4.10:

`import { ResourceModule } from 'ng2-resource-rest';`
causes:
`index.js does not export ResourceModule`

**Comment by troyanskiy** [comment]
@vlados Please try v 1.5.0
