### ISSUE TITLE
Module or jsnext:main in package.json

### ISSUE THREAD

**Issue by danbucholtz** [troyanskiy/ng2-resource-rest#45]
Since this is a Typescript app, can you distribute `es5` code (es5 target) with `es2015` modules in addition to the `commonjs` modules you distribute?

Set the `moduleResolution` to `node` as well to make everything work well in the `tsconfig.json`.

`jsnext:main` and `module` are the fields that point to the entrypoint for the es5 code with es2015 modules. Angular uses `module` and it seems most bundlers look for `module`, then `jsnext:main`, then `main` in that order.

Thanks,
Dan

**Comment by troyanskiy** [comment]
Thanks a lot! Please try v 1.5.0

**Comment by danbucholtz** [comment]
Thanks @troyanskiy!

Thanks,
Dan
