### ISSUE TITLE
ODATA

### ISSUE THREAD

**Issue by beradrian** [troyanskiy/ng2-resource-rest#52]
This is more like a question than an issue.

I'm trying to use your library along with ODATA. I was thinking that the best way to do it will be to create a `ODATAResource` class that extends `Resource`. Then I will override the `_getPath` method to return the class name. Finally I will implement the ODATA methods as for any resource.

Then when I'll need a specific resource is enough just to extend the ODATAResource and I'll have everything already defined.

What do you think? Is this a good approach?

**Comment by troyanskiy** [comment]
Hello @beradrian .
I have never worked with ODATA. If you are 100% sure that your resource class name will be used in path, than yes, you can overwrite `_getPath` or `getPath` methods. Otherwise better to define path for each request separately.

**Comment by beradrian** [comment]
By default, the path will be the class name (or start with it). What's the difference between `_getPath` and `getPath`? Which one should I override in this case?

**Comment by beradrian** [comment]
And another question - what will be the best way to define the base URL across all resources?

**Comment by beradrian** [comment]
There's also the problem that `_getPath` is marked as private.

**Comment by troyanskiy** [comment]
@beradrian so the best for you will be override `getPath` method, not `_getPath`. 
To define global base URL is better to use static class somewhere in your app component:
```ts
ResourceGlobalConfig.url = 'https://api.mydomain.com'
```

**Comment by beradrian** [comment]
And if I override `getPath` can I still use the path property of the annotation?

**Comment by beradrian** [comment]
I have the following
```
export class ODATAResource<R> extends Resource {

	@ResourceAction({
		path: '/{!id}'
	})
	get: ResourceMethod<{id: any}, R>;

	getPath(): string | Promise<string> {
		return "/" + this.getPlural();
	}

	private getName() {
		return (<any>this).constructor.name;
	}

	private getPlural() {
		return this.getName() + "s";
	}
}


@Injectable()
@ResourceParams()
export class UserResource extends ODATAResource<User> {
}
```

The problem is that when I call `userResource.get({id: "1"})` the URL _http://localhost/1_ gets called instead of _http://localhost/Users/1_ as I would have expected. Am I missing something?

**Comment by troyanskiy** [comment]
In your case `getPath` is also overridden by method decorator
```ts
    @ResourceAction({
        path: '/{!id}'
    })
    get: ResourceMethod<{id: any}, R>;
```

**Comment by troyanskiy** [comment]
So to resolve that I think better to override `getUrl`, which will return full path with your class name. In that case you can decorate methods with `path` param.
``` ts
export class ODATAResource<R> extends Resource {

    @ResourceAction({
        path: '/{!id}'
    })
    get: ResourceMethod<{id: any}, R>;

    getUrl(): string | Promise<string> {
        return super.getUrl() + "/" + this.getPlural();
    }

    private getName() {
        return (<any>this).constructor.name;
    }

    private getPlural() {
        return this.getName() + "s";
    }
}


@Injectable()
@ResourceParams()
export class UserResource extends ODATAResource<User> {
}
```

**Comment by beradrian** [comment]
I would have expected that the url/path of the method to be relative to the one of the class, which will also be relative to the global one.

Anyway, wanted to thank you for a great library.
