### ISSUE TITLE
Error CORS with Safari

### ISSUE THREAD

**Issue by jcga82** [troyanskiy/ng2-resource-rest#53]
Error: Failed to load resource: Request header field Cache-Control is not allowed by Access-Control-Allow-Headers.

With Chrome work fine.

**Comment by troyanskiy** [comment]
Hello.
Please google the problem.
It's related to server-browse security.
http://stackoverflow.com/questions/26243364/ajax-request-header-field-key-is-not-allowed-by-access-control-allow-headers
