### ISSUE TITLE
Generating resources

### ISSUE THREAD

**Issue by laserus** [troyanskiy/ng2-resource-rest#54]
Hello,

We have a plenty of resources (e.g. 30), which are different only by name and could do various things and have different. 

Previously (in angular 1) we have used ngResource: 
https://github.com/angular/angular.js/blob/master/src/ngResource/resource.js
which had CRUD methods and abstract resources.

`$resource(path, id, etc)` did everything (we could parameterize with uri). 

With ng2-resource-rest can I create such abstract method?

E.g. 
```
class AbstractResource extend Resource{
  path: string;
  constructor(config:GlobalConfig, method:string)
    this.path = config.makePath(method)
  }
}
```

Alternatively, I could create a list of 
```
@Injectable()
@ResourceParams({
  url: makePath(MyRes1)
})
export class MyRes1 extends ResourceCRUD<any, any, any> {}

@Injectable()
@ResourceParams({
  url: makePath(MyRes2)
})
export class MyRes2 extends ResourceCRUD<any, any, any> {}
```

But, the problem is that the path is prefixed (I will know it only at runtime).

PS: I do not want to lose benefits of aot, thus do it without dynamic compiling.

Thanks!

**Comment by troyanskiy** [comment]
Hello.
You can override `getPath` or/and `getUrl` methods.
```ts
class AbstractResource extend Resource{
  getPath(): string | Promise<string> {
     // here return your path.
     // it will be executed every time before request.
  }
}
```

or without overriding
```ts
class AbstractResource extend Resource {
  constructor(config:GlobalConfig, method:string)
    this.setPath(config.makePath(method));
  }
}
```

**Comment by laserus** [comment]
Thanks!
