### ISSUE TITLE
How can I send out a array?

### ISSUE THREAD

**Issue by ruiyeah** [troyanskiy/ng2-resource-rest#55]
Hello,

one of our server's interface need the params that are instance of Array.

However,when I want to send out the data of Array,the resource parse it to a object and then stringify it automatically.

So how can i send out the data as an array?

thanks for your answer!

**Comment by troyanskiy** [comment]
Hello.
How do you send the data? POST or GET.
Could you please give me an example of the data, how it sending now and how it should be expected?

**Comment by ruiyeah** [comment]
Post or put.

For example,the data is just like
` [
    {startTime:'2016-11-15'},
    {startTime:'2016-11-15'}
]`

My expected is just the same as above that send out like an array,but the current data that send out is just like:

`{"0":{"startTime":"2016-11-15"},"1":{"startTime":"2016-11-15"}}`

**Comment by troyanskiy** [comment]
I have made some fixes.
Could you please update 1.5.4 version and test it for me?
Thanks for the issue.

**Comment by ruiyeah** [comment]
It is OK.
Thank you~
