### ISSUE TITLE
/node_modules/ng2-resource-rest/ 403 (Forbidden)

### ISSUE THREAD

**Issue by iloveyo123u1** [troyanskiy/ng2-resource-rest#6]
i used angular@2.0.0-bete.13

-------------------------------------------------
system.src.js:1154 GET http://127.0.0.1/node_modules/ng2-resource-rest/ 403 (Forbidden)fetchTextFromURL @ system.src.js:1154(anonymous function) @ system.src.js:1710ZoneAwarePromise @ angular2-polyfills.js:589(anonymous function) @ system.src.js:1709(anonymous function) @ system.src.js:2734(anonymous function) @ system.src.js:3308(anonymous function) @ system.src.js:3575(anonymous function) @ system.src.js:3960(anonymous function) @ system.src.js:4419(anonymous function) @ system.src.js:4671(anonymous function) @ system.src.js:406ZoneDelegate.invoke @ angular2-polyfills.js:332Zone.run @ angular2-polyfills.js:227(anonymous function) @ angular2-polyfills.js:576ZoneDelegate.invokeTask @ angular2-polyfills.js:365Zone.runTask @ angular2-polyfills.js:263drainMicroTaskQueue @ angular2-polyfills.js:482ZoneTask.invoke @ angular2-polyfills.js:434
angular2-polyfills.js:332 Error: Error: XHR error (403 Forbidden) loading http://127.0.0.1/node_modules/ng2-resource-rest(…)ZoneDelegate.invoke @ angular2-polyfills.js:332Zone.run @ angular2-polyfills.js:227(anonymous function) @ angular2-polyfills.js:576ZoneDelegate.invokeTask @ angular2-polyfills.js:365Zone.runTask @ angular2-polyfills.js:263drainMicroTaskQueue @ angular2-polyfills.js:482ZoneTask.invoke @ angular2-polyfills.js:434

---------------------------------------------

angular2-quickstart@1.0.0 /code/web/my/ngApp
├── @angular2-material/button@2.0.0-alpha.2
├── @angular2-material/card@2.0.0-alpha.2
├── @angular2-material/checkbox@2.0.0-alpha.2
├── @angular2-material/core@2.0.0-alpha.2
├── @angular2-material/progress-circle@2.0.0-alpha.2
├── @angular2-material/radio@2.0.0-alpha.2
├── @angular2-material/sidenav@2.0.0-alpha.2
├── @angular2-material/toolbar@2.0.0-alpha.2
├── angular2@2.0.0-beta.13
├─┬ concurrently@2.0.0
│ ├── bluebird@2.9.6
│ ├─┬ chalk@0.5.1
│ │ ├── ansi-styles@1.1.0
│ │ ├── escape-string-regexp@1.0.5
│ │ ├─┬ has-ansi@0.1.0
│ │ │ └── ansi-regex@0.2.1
│ │ ├── strip-ansi@0.3.0
│ │ └── supports-color@0.2.0
│ ├── commander@2.6.0
│ ├─┬ cross-spawn@0.2.9
│ │ └── lru-cache@2.7.3
│ ├── lodash@3.1.0
│ ├── moment@2.12.0
│ └── rx@2.3.24
├── es6-promise@3.0.2 extraneous
├── es6-shim@0.35.0
├─┬ lite-server@2.2.0
│ ├─┬ browser-sync@2.11.2
│ │ ├── async-each-series@0.1.1
│ │ ├─┬ browser-sync-client@2.4.1
│ │ │ ├── etag@1.7.0
│ │ │ └── fresh@0.3.0
│ │ ├─┬ browser-sync-ui@0.5.18
│ │ │ ├─┬ stream-throttle@0.1.3
│ │ │ │ └── limiter@1.1.0
│ │ │ └─┬ weinre@2.0.0-pre-I0Z7U9OV
│ │ │   ├─┬ express@2.5.11
│ │ │   │ ├─┬ connect@1.9.2
│ │ │   │ │ └── formidable@1.0.17
│ │ │   │ ├── mime@1.2.4
│ │ │   │ ├── mkdirp@0.3.0
│ │ │   │ └── qs@0.4.2
│ │ │   ├── nopt@3.0.6
│ │ │   └── underscore@1.7.0
│ │ ├── bs-recipes@1.2.2
│ │ ├─┬ chokidar@1.4.1
│ │ │ ├── anymatch@1.3.0
│ │ │ ├── async-each@0.1.6
│ │ │ ├── UNMET OPTIONAL DEPENDENCY fsevents@^1.0.0
│ │ │ ├── glob-parent@2.0.0
│ │ │ ├── inherits@2.0.1
│ │ │ ├─┬ is-binary-path@1.0.1
│ │ │ │ └── binary-extensions@1.4.0
│ │ │ ├── is-glob@2.0.1
│ │ │ ├── path-is-absolute@1.0.0
│ │ │ └─┬ readdirp@2.0.0
│ │ │   └─┬ readable-stream@2.0.6
│ │ │     ├── core-util-is@1.0.2
│ │ │     ├── isarray@1.0.0
│ │ │     ├── process-nextick-args@1.0.6
│ │ │     ├── string_decoder@0.10.31
│ │ │     └── util-deprecate@1.0.2
│ │ ├─┬ connect@3.4.1
│ │ │ ├─┬ finalhandler@0.4.1
│ │ │ │ ├─┬ on-finished@2.3.0
│ │ │ │ │ └── ee-first@1.1.1
│ │ │ │ └── unpipe@1.0.0
│ │ │ ├── parseurl@1.3.1
│ │ │ └── utils-merge@1.0.0
│ │ ├── dev-ip@1.0.1
│ │ ├─┬ easy-extender@2.3.2
│ │ │ └── lodash@3.10.1
│ │ ├─┬ eazy-logger@2.1.3
│ │ │ ├─┬ lodash.clonedeep@4.3.1
│ │ │ │ └── lodash._baseclone@4.5.4
│ │ │ ├─┬ opt-merger@1.1.1
│ │ │ │ └── lodash@3.10.1
│ │ │ └─┬ tfunk@3.0.2
│ │ │   ├─┬ chalk@1.1.3
│ │ │   │ ├── ansi-styles@2.2.1
│ │ │   │ ├─┬ has-ansi@2.0.0
│ │ │   │ │ └── ansi-regex@2.0.0
│ │ │   │ ├── strip-ansi@3.0.1
│ │ │   │ └── supports-color@2.0.0
│ │ │   └── object-path@0.9.2
│ │ ├── emitter-steward@1.0.0
│ │ ├─┬ foxy@11.1.5
│ │ │ ├─┬ http-proxy@1.13.2
│ │ │ │ ├── eventemitter3@1.2.0
│ │ │ │ └── requires-port@1.0.0
│ │ │ ├─┬ lodash.merge@3.3.2
│ │ │ │ ├── lodash._arraycopy@3.0.0
│ │ │ │ ├── lodash._arrayeach@3.0.0
│ │ │ │ ├─┬ lodash._createassigner@3.1.1
│ │ │ │ │ ├── lodash._bindcallback@3.0.1
│ │ │ │ │ ├── lodash._isiterateecall@3.0.9
│ │ │ │ │ └── lodash.restparam@3.6.1
│ │ │ │ ├── lodash._getnative@3.9.1
│ │ │ │ ├── lodash.isarguments@3.0.8
│ │ │ │ ├── lodash.isarray@3.0.4
│ │ │ │ ├─┬ lodash.isplainobject@3.2.0
│ │ │ │ │ └── lodash._basefor@3.0.3
│ │ │ │ ├── lodash.istypedarray@3.0.6
│ │ │ │ ├── lodash.keys@3.1.2
│ │ │ │ ├── lodash.keysin@3.0.8
│ │ │ │ └─┬ lodash.toplainobject@3.0.0
│ │ │ │   └── lodash._basecopy@3.0.1
│ │ │ └── resp-modifier@4.0.4
│ │ ├─┬ fs-extra@0.26.7
│ │ │ ├── jsonfile@2.2.3
│ │ │ └── klaw@1.1.3
│ │ ├── immutable@3.7.6
│ │ ├─┬ localtunnel@1.8.1
│ │ │ ├── openurl@1.1.0
│ │ │ ├─┬ request@2.65.0
│ │ │ │ ├── aws-sign2@0.6.0
│ │ │ │ ├── bl@1.0.3
│ │ │ │ ├── caseless@0.11.0
│ │ │ │ ├─┬ combined-stream@1.0.5
│ │ │ │ │ └── delayed-stream@1.0.0
│ │ │ │ ├── extend@3.0.0
│ │ │ │ ├── forever-agent@0.6.1
│ │ │ │ ├─┬ form-data@1.0.0-rc4
│ │ │ │ │ └── async@1.5.2
│ │ │ │ ├─┬ har-validator@2.0.6
│ │ │ │ │ ├─┬ chalk@1.1.3
│ │ │ │ │ │ ├── ansi-styles@2.2.1
│ │ │ │ │ │ ├─┬ has-ansi@2.0.0
│ │ │ │ │ │ │ └── ansi-regex@2.0.0
│ │ │ │ │ │ ├── strip-ansi@3.0.1
│ │ │ │ │ │ └── supports-color@2.0.0
│ │ │ │ │ ├─┬ commander@2.9.0
│ │ │ │ │ │ └── graceful-readlink@1.0.1
│ │ │ │ │ ├─┬ is-my-json-valid@2.13.1
│ │ │ │ │ │ ├── generate-function@2.0.0
│ │ │ │ │ │ ├─┬ generate-object-property@1.2.0
│ │ │ │ │ │ │ └── is-property@1.0.2
│ │ │ │ │ │ └── jsonpointer@2.0.0
│ │ │ │ │ └─┬ pinkie-promise@2.0.0
│ │ │ │ │   └── pinkie@2.0.4
│ │ │ │ ├─┬ hawk@3.1.3
│ │ │ │ │ ├── boom@2.10.1
│ │ │ │ │ ├── cryptiles@2.0.5
│ │ │ │ │ ├── hoek@2.16.3
│ │ │ │ │ └── sntp@1.0.9
│ │ │ │ ├─┬ http-signature@0.11.0
│ │ │ │ │ ├── asn1@0.1.11
│ │ │ │ │ ├── assert-plus@0.1.5
│ │ │ │ │ └── ctype@0.5.3
│ │ │ │ ├── isstream@0.1.2
│ │ │ │ ├── json-stringify-safe@5.0.1
│ │ │ │ ├── node-uuid@1.4.7
│ │ │ │ ├── oauth-sign@0.8.1
│ │ │ │ ├── qs@5.2.0
│ │ │ │ ├── stringstream@0.0.5
│ │ │ │ └── tunnel-agent@0.4.2
│ │ │ └─┬ yargs@3.29.0
│ │ │   ├── camelcase@1.2.1
│ │ │   ├─┬ cliui@3.1.2
│ │ │   │ ├─┬ strip-ansi@3.0.1
│ │ │   │ │ └── ansi-regex@2.0.0
│ │ │   │ └── wrap-ansi@2.0.0
│ │ │   ├── decamelize@1.2.0
│ │ │   ├─┬ os-locale@1.4.0
│ │ │   │ └─┬ lcid@1.0.0
│ │ │   │   └── invert-kv@1.0.0
│ │ │   ├── window-size@0.1.4
│ │ │   └── y18n@3.2.1
│ │ ├── lodash@3.10.1
│ │ ├── longest@1.0.1
│ │ ├─┬ meow@3.3.0
│ │ │ ├─┬ camelcase-keys@1.0.0
│ │ │ │ └── map-obj@1.0.1
│ │ │ ├─┬ indent-string@1.2.2
│ │ │ │ ├── get-stdin@4.0.1
│ │ │ │ └── repeating@1.1.3
│ │ │ └── object-assign@3.0.0
│ │ ├─┬ micromatch@2.3.5
│ │ │ ├─┬ arr-diff@2.0.0
│ │ │ │ └── arr-flatten@1.0.1
│ │ │ ├── array-unique@0.2.1
│ │ │ ├─┬ braces@1.8.3
│ │ │ │ ├─┬ expand-range@1.8.1
│ │ │ │ │ └─┬ fill-range@2.2.3
│ │ │ │ │   ├── is-number@2.1.0
│ │ │ │ │   ├── randomatic@1.1.5
│ │ │ │ │   └── repeat-string@1.5.4
│ │ │ │ ├── preserve@0.2.0
│ │ │ │ └── repeat-element@1.1.2
│ │ │ ├─┬ expand-brackets@0.1.5
│ │ │ │ └── is-posix-bracket@0.1.1
│ │ │ ├── extglob@0.3.2
│ │ │ ├── filename-regex@2.0.0
│ │ │ ├── is-extglob@1.0.0
│ │ │ ├─┬ kind-of@3.0.2
│ │ │ │ └── is-buffer@1.1.3
│ │ │ ├── lazy-cache@0.2.7
│ │ │ ├── normalize-path@2.0.1
│ │ │ ├─┬ object.omit@2.0.0
│ │ │ │ ├─┬ for-own@0.1.4
│ │ │ │ │ └── for-in@0.1.5
│ │ │ │ └── is-extendable@0.1.1
│ │ │ ├─┬ parse-glob@3.0.4
│ │ │ │ ├── glob-base@0.3.0
│ │ │ │ └── is-dotfile@1.0.2
│ │ │ └─┬ regex-cache@0.4.3
│ │ │   ├── is-equal-shallow@0.1.3
│ │ │   └── is-primitive@2.0.0
│ │ ├─┬ opn@3.0.3
│ │ │ └── object-assign@4.0.1
│ │ ├─┬ portscanner@1.0.0
│ │ │ └── async@0.1.15
│ │ ├─┬ query-string@2.4.2
│ │ │ └── strict-uri-encode@1.1.0
│ │ ├─┬ resp-modifier@5.0.2
│ │ │ └─┬ minimatch@2.0.10
│ │ │   └─┬ brace-expansion@1.1.3
│ │ │     ├── balanced-match@0.3.0
│ │ │     └── concat-map@0.0.1
│ │ ├─┬ serve-index@1.7.3
│ │ │ ├─┬ accepts@1.2.13
│ │ │ │ └── negotiator@0.5.3
│ │ │ ├── batch@0.5.3
│ │ │ ├── escape-html@1.0.3
│ │ │ ├─┬ http-errors@1.3.1
│ │ │ │ └── statuses@1.2.1
│ │ │ └─┬ mime-types@2.1.10
│ │ │   └── mime-db@1.22.0
│ │ ├─┬ serve-static@1.10.2
│ │ │ └─┬ send@0.13.1
│ │ │   ├── depd@1.1.0
│ │ │   ├── destroy@1.0.4
│ │ │   ├── mime@1.3.4
│ │ │   └── range-parser@1.0.3
│ │ ├─┬ socket.io@1.4.5
│ │ │ ├─┬ engine.io@1.6.8
│ │ │ │ ├─┬ accepts@1.1.4
│ │ │ │ │ ├─┬ mime-types@2.0.14
│ │ │ │ │ │ └── mime-db@1.12.0
│ │ │ │ │ └── negotiator@0.4.9
│ │ │ │ ├── base64id@0.1.0
│ │ │ │ ├─┬ engine.io-parser@1.2.4
│ │ │ │ │ ├── after@0.8.1
│ │ │ │ │ ├── arraybuffer.slice@0.0.6
│ │ │ │ │ ├── base64-arraybuffer@0.1.2
│ │ │ │ │ ├── blob@0.0.4
│ │ │ │ │ ├── has-binary@0.1.6
│ │ │ │ │ └── utf8@2.1.0
│ │ │ │ └─┬ ws@1.0.1
│ │ │ │   ├── options@0.0.6
│ │ │ │   └── ultron@1.0.2
│ │ │ ├─┬ has-binary@0.1.7
│ │ │ │ └── isarray@0.0.1
│ │ │ ├─┬ socket.io-adapter@0.4.0
│ │ │ │ └─┬ socket.io-parser@2.2.2
│ │ │ │   ├── debug@0.7.4
│ │ │ │   └── json3@3.2.6
│ │ │ ├─┬ socket.io-client@1.4.5
│ │ │ │ ├── backo2@1.0.2
│ │ │ │ ├── component-bind@1.0.0
│ │ │ │ ├── component-emitter@1.2.0
│ │ │ │ ├─┬ engine.io-client@1.6.8
│ │ │ │ │ ├── component-inherit@0.0.3
│ │ │ │ │ ├── has-cors@1.1.0
│ │ │ │ │ ├── parsejson@0.0.1
│ │ │ │ │ ├── parseqs@0.0.2
│ │ │ │ │ ├── xmlhttprequest-ssl@1.5.1
│ │ │ │ │ └── yeast@0.1.2
│ │ │ │ ├── indexof@0.0.1
│ │ │ │ ├── object-component@0.0.3
│ │ │ │ ├─┬ parseuri@0.0.4
│ │ │ │ │ └─┬ better-assert@1.0.2
│ │ │ │ │   └── callsite@1.0.0
│ │ │ │ └── to-array@0.1.4
│ │ │ └─┬ socket.io-parser@2.2.6
│ │ │   ├── benchmark@1.0.0
│ │ │   ├── component-emitter@1.1.2
│ │ │   └── json3@3.3.2
│ │ ├── ua-parser-js@0.7.10
│ │ └── ucfirst@1.0.0
│ ├── connect-history-api-fallback@1.2.0
│ ├── connect-logger@0.0.1
│ ├── lodash@4.8.2
│ └── minimist@1.2.0
├── ng2-material@0.3.4
├── ng2-resource-rest@0.2.2
├── reflect-metadata@0.1.2
├── rxjs@5.0.0-beta.2
├─┬ systemjs@0.19.25
│ └── when@3.7.7
├── typescript@1.8.9
├─┬ typings@0.7.12
│ ├── any-promise@1.1.0
│ ├── archy@1.0.0
│ ├── bluebird@3.3.4
│ ├─┬ chalk@1.1.3
│ │ ├── ansi-styles@2.2.1
│ │ ├─┬ has-ansi@2.0.0
│ │ │ └── ansi-regex@2.0.0
│ │ ├── strip-ansi@3.0.1
│ │ └── supports-color@2.0.0
│ ├─┬ columnify@1.5.4
│ │ ├─┬ strip-ansi@3.0.1
│ │ │ └── ansi-regex@2.0.0
│ │ └─┬ wcwidth@1.0.0
│ │   └─┬ defaults@1.0.3
│ │     └── clone@1.0.2
│ ├── listify@1.0.0
│ ├─┬ typings-core@0.2.15
│ │ ├── array-uniq@1.0.2
│ │ ├─┬ configstore@2.0.0
│ │ │ ├─┬ dot-prop@2.4.0
│ │ │ │ └── is-obj@1.0.1
│ │ │ ├─┬ mkdirp@0.5.1
│ │ │ │ └── minimist@0.0.8
│ │ │ ├── object-assign@4.0.1
│ │ │ ├── os-tmpdir@1.0.1
│ │ │ ├─┬ osenv@0.1.3
│ │ │ │ └── os-homedir@1.0.1
│ │ │ ├── uuid@2.0.1
│ │ │ ├─┬ write-file-atomic@1.1.4
│ │ │ │ ├── imurmurhash@0.1.4
│ │ │ │ └── slide@1.1.6
│ │ │ └── xdg-basedir@2.0.0
│ │ ├─┬ debug@2.2.0
│ │ │ └── ms@0.7.1
│ │ ├─┬ detect-indent@4.0.0
│ │ │ └─┬ repeating@2.0.0
│ │ │   └─┬ is-finite@1.0.1
│ │ │     └── number-is-nan@1.0.0
│ │ ├── graceful-fs@4.1.3
│ │ ├─┬ has@1.0.1
│ │ │ └── function-bind@1.1.0
│ │ ├─┬ invariant@2.2.1
│ │ │ └─┬ loose-envify@1.1.0
│ │ │   └── js-tokens@1.0.3
│ │ ├─┬ is-absolute@0.2.5
│ │ │ ├─┬ is-relative@0.2.1
│ │ │ │ └─┬ is-unc-path@0.1.1
│ │ │ │   └── unc-path-regex@0.1.1
│ │ │ └── is-windows@0.1.1
│ │ ├── lockfile@1.0.1
│ │ ├─┬ make-error-cause@1.1.0
│ │ │ └── make-error@1.1.1
│ │ ├─┬ mkdirp@0.5.1
│ │ │ └── minimist@0.0.8
│ │ ├─┬ object.pick@1.1.2
│ │ │ └── isobject@2.0.0
│ │ ├─┬ parse-json@2.2.0
│ │ │ └─┬ error-ex@1.3.0
│ │ │   └── is-arrayish@0.2.1
│ │ ├─┬ popsicle@5.0.1
│ │ │ ├── arrify@1.0.1
│ │ │ ├─┬ concat-stream@1.5.1
│ │ │ │ └── typedarray@0.0.6
│ │ │ ├─┬ form-data@0.2.0
│ │ │ │ ├── async@0.9.2
│ │ │ │ ├─┬ combined-stream@0.0.7
│ │ │ │ │ └── delayed-stream@0.0.5
│ │ │ │ └─┬ mime-types@2.0.14
│ │ │ │   └── mime-db@1.12.0
│ │ │ ├── methods@1.1.2
│ │ │ └── tough-cookie@2.2.2
│ │ ├─┬ popsicle-proxy-agent@1.0.0
│ │ │ ├─┬ http-proxy-agent@1.0.0
│ │ │ │ └── agent-base@2.0.1
│ │ │ └── https-proxy-agent@1.0.0
│ │ ├── popsicle-retry@2.0.0
│ │ ├── popsicle-status@1.0.2
│ │ ├── promise-finally@2.1.0
│ │ ├─┬ rc@1.1.6
│ │ │ ├── deep-extend@0.4.1
│ │ │ ├── ini@1.3.4
│ │ │ └── strip-json-comments@1.0.4
│ │ ├─┬ rimraf@2.5.2
│ │ │ └─┬ glob@7.0.3
│ │ │   ├─┬ inflight@1.0.4
│ │ │   │ └── wrappy@1.0.1
│ │ │   └── once@1.3.3
│ │ ├─┬ sort-keys@1.1.1
│ │ │ └── is-plain-obj@1.1.0
│ │ ├── string-template@1.0.0
│ │ ├─┬ strip-bom@2.0.0
│ │ │ └── is-utf8@0.2.1
│ │ ├── thenify@3.2.0
│ │ ├── throat@2.0.2
│ │ ├─┬ touch@1.0.0
│ │ │ └─┬ nopt@1.0.10
│ │ │   └── abbrev@1.0.7
│ │ └── zip-object@0.1.0
│ ├─┬ update-notifier@0.6.3
│ │ ├─┬ boxen@0.3.1
│ │ │ ├─┬ chalk@1.1.3
│ │ │ │ ├── ansi-styles@2.2.1
│ │ │ │ ├─┬ has-ansi@2.0.0
│ │ │ │ │ └── ansi-regex@2.0.0
│ │ │ │ ├── strip-ansi@3.0.1
│ │ │ │ └── supports-color@2.0.0
│ │ │ ├── filled-array@1.1.0
│ │ │ ├── object-assign@4.0.1
│ │ │ ├── repeating@2.0.0
│ │ │ ├─┬ string-width@1.0.1
│ │ │ │ ├── code-point-at@1.0.0
│ │ │ │ ├── is-fullwidth-code-point@1.0.0
│ │ │ │ └─┬ strip-ansi@3.0.1
│ │ │ │   └── ansi-regex@2.0.0
│ │ │ └── widest-line@1.0.0
│ │ ├─┬ chalk@1.1.3
│ │ │ ├── ansi-styles@2.2.1
│ │ │ ├─┬ has-ansi@2.0.0
│ │ │ │ └── ansi-regex@2.0.0
│ │ │ ├── strip-ansi@3.0.1
│ │ │ └── supports-color@2.0.0
│ │ ├── is-npm@1.0.0
│ │ ├─┬ latest-version@2.0.0
│ │ │ └─┬ package-json@2.3.1
│ │ │   ├─┬ got@5.5.0
│ │ │   │ ├─┬ create-error-class@2.0.1
│ │ │   │ │ └── capture-stack-trace@1.0.0
│ │ │   │ ├── duplexer2@0.1.4
│ │ │   │ ├── is-redirect@1.0.0
│ │ │   │ ├── is-retry-allowed@1.0.0
│ │ │   │ ├── is-stream@1.0.1
│ │ │   │ ├── lowercase-keys@1.0.0
│ │ │   │ ├── node-status-codes@1.0.0
│ │ │   │ ├── object-assign@4.0.1
│ │ │   │ ├── read-all-stream@3.1.0
│ │ │   │ ├── timed-out@2.0.0
│ │ │   │ ├── unzip-response@1.0.0
│ │ │   │ └─┬ url-parse-lax@1.0.0
│ │ │   │   └── prepend-http@1.0.3
│ │ │   ├── registry-url@3.0.3
│ │ │   └── semver@5.1.0
│ │ └─┬ semver-diff@2.1.0
│ │   └── semver@5.0.3
│ ├── wordwrap@1.0.0
│ └── xtend@4.0.1
└── zone.js@0.6.6

npm ERR! extraneous: es6-promise@3.0.2 /code/web/my/ngApp/node_modules/es6-promise

---------------------------------------------
my js config:

  
  <script>
     System.config({
      map: {
        "ng2-material":"node_modules/ng2-material",
        "ng2-resource-rest":"node_modules/ng2-resource-rest",
       },

 
      packages: {
        app: {
          format: 'register',
          defaultExtension: 'js'
        },
        'ng2-material': {
          defaultExtension: 'js'
        },
        'ng2-resource-rest': {
          defaultExtension: 'js'
        }

      }
    });
    System.import('app/main')
            .then(null, console.error.bind(console));
  </script>

**Comment by iloveyo123u1** [comment]
```
 System.config({
      map: {
        "ng2-material":"node_modules/ng2-material",
        "ng2-resource-rest":"node_modules/ng2-resource-rest",

      },

      packages: {
        app: {
          format: 'register',
          defaultExtension: 'js'
        },
        'ng2-material': {
          defaultExtension: 'js'
        },
        'ng2-resource-rest': {
          defaultExtension: 'js'
        }


      }
    });
    System.import('app/main')
            .then(null, console.error.bind(console));
```

**Comment by iloveyo123u1** [comment]
can you help me

**Comment by troyanskiy** [comment]
I am sorry but unfortunately I can't help you with that. I have never used angular2 (pure).
Let me know you you will find the solution or fix.

**Comment by iloveyo123u1** [comment]
i fix this bug

chang 2 files ->
index.ts
index.d.ts

// import "rxjs";
import "rxjs/Rx";


please read http://www.mzan.com/article/36239813-angular2-rxjs-404-error.shtml

**Comment by iloveyo123u1** [comment]
please close this  issues  , thank you
