### ISSUE TITLE
Response header

### ISSUE THREAD

**Issue by norbert-tasi** [troyanskiy/ng2-resource-rest#60]
Hello,

For pagination I have info in the response header, but it seems it is cleared out somehow. I couldn't find the cause. In the responseInterceptor only the content-type remains.

Could you help me?

Thanks

**Comment by troyanskiy** [comment]
Hello,
Are you doing cross domain request or within same domain and same port?
I have a felling that it's cross domain request and browser does not provide the headers to JS.
In that case your server should add some extra headers to response. Please check [here].(https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS)

If it's not cross domain request, please provide your code examples.

**Comment by norbert-tasi** [comment]
You are right! I've had to add it to Access-Control-Expose-Headers.
 Thank you very much!

**Comment by troyanskiy** [comment]
Always welcome.
