### ISSUE TITLE
withCredentials

### ISSUE THREAD

**Issue by ybrodsky** [troyanskiy/ng2-resource-rest#61]
What would be the proper way to set the withCredentials option:

Angular example:

`this.http.get(this.url, {withCredentials: true})......`

Thanks a lot.

**Comment by troyanskiy** [comment]
It's not possible yet...
I will add it now

**Comment by troyanskiy** [comment]
Now you can use withCredentials option to all resource class of to specific method.

``` ts
@ResourceParams({
    withCredentials: true
})
export class MyResource extends Resource {

}
```

``` ts
@ResourceParams()
export class MyResource extends Resource {
  @ResourceAction({
    isArray: true
  })
  query: ResourceMethod<IQueryInput, INewsShort[]>;

  @ResourceAction({
    path: '/{!id}',
    withCredentials: true
  })
  get: ResourceMethod<{id: any}, INews>;

}
```

**Comment by ybrodsky** [comment]
That was fast.
Thanks a lot.

**Comment by troyanskiy** [comment]
@ybrodsky You are welcome. I'm closing the issue.
