### ISSUE TITLE
ResourceAction.js:243 Returned data should be an array. Received Object...

### ISSUE THREAD

**Issue by gasparherrera** [troyanskiy/ng2-resource-rest#64]
Hi, congrats on a great app, thank you very much.

I need help getting around the error "ResourceAction.js:243 Returned data should be an array. Received Object...". This happens when using Django REST framework's paginated response which has the schema:

received: {
    results: Array[n],
    next: string,
    prev: string,
    count: number
}

As you see, the results from the query access come in the "result" parameter, not in the root, hence the error. 

As I understand one could map this response in your application, that is, to configure that this schema is how the data comes from the API, but I know not where or how, could you please assist me?.

**Comment by troyanskiy** [comment]
Hi. It depends what you need finally.
If you just need result array without next, prev, count data then you can create response interceptor for method like that:

```ts
import { ResourceMethod, Resource, ResourceParams, ResourceAction } from 'ng2-resource-rest';
import { Request, Response } from '@angular/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';

@Injectable()
@ResourceParams({
  url: 'https://domain.net/api/users'
})
export class NewsRes extends Resource {

  @ResourceAction({
    isArray: true,
    responseInterceptor: (observable: Observable<Response>, request?: Request): Observable<any> => {
      return observable.map(res => res.json().results);
    }
  })
  query: ResourceMethod<IQueryInput, INewsShort[]>;

}

```

Please let me know if it resolves your problem.

**Comment by gasparherrera** [comment]
I need the count variable from the API. 

`export class NewsRes extends Resource {

  @ResourceAction({
    isArray: true,
    responseInterceptor: (observable: Observable<Response>, request?: Request): Observable<any> => {
      return observable.map(res => res.json().results, count => res.json().count);
    }
  })
  query: ResourceMethod<IQueryInput, INewsShort[]>;

}`

Something like that ?

**Comment by troyanskiy** [comment]
In that case you should not receive an array. You will need receive an object with array inside.
In that case you don't need any response interceptors.

```ts
import { ResourceMethod, Resource, ResourceParams, ResourceAction } from 'ng2-resource-rest';
import { Request, Response } from '@angular/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';

export interface IData {
  results: any[];
  next: string;
  prev: string;
  count: number;
}

@Injectable()
@ResourceParams({
  url: 'https://domain.net/api/users'
})
export class NewsRes extends Resource {

  @ResourceAction({
    path: '/path/to/api'
  })
  query: ResourceMethod<any, IData>;

}
```

**Comment by gasparherrera** [comment]
of course !, thx

**Comment by troyanskiy** [comment]
Did you try to override query method of ResourceCRUD?

**Comment by gasparherrera** [comment]
I'm sorry I fail to see how to override it. I'm sure it's because of my ignorance of Angular 2 programming, could you lend me a hand?.

**Comment by troyanskiy** [comment]
```typescript
@Injectable()
@ResourceParams({
  url: 'https://domain.net/api/users'
})
export class NewsRes extends ResourceCRUD<UQueryInput, CShort, CFull> {

  @ResourceAction({
    isArray: true,
    responseInterceptor: (observable: Observable<Response>, request?: Request): Observable<any> => {
      return observable.map(res => res.json().results);
    }
  })
  query: ResourceMethod<IQueryInput, CShort[]>;

}
```

Hope it will help.

**Comment by gasparherrera** [comment]
Now it works perfectly, thank you very much

**Comment by gasparherrera** [comment]
I'm sorry to ask again, but this is a detail. The programing you suggested works, it runs on the angular app and the django server, however when I compile wepack (angular-cli) throws:


Class 'ClienteResource' incorrectly extends base class 'ResourceCRUD<UQueryInput, CShort, Cliente>'.
  Types of property 'query' are incompatible.
    Type 'ResourceMethod<UQueryInput, IData>' is not assignable to type 'ResourceMethod<UQueryInput, CShort[]>'.
      Type 'IData' is not assignable to type 'CShort[]'.
        Property 'find' is missing in type 'IData'.
[default] Checking finished with 1 errors



I've tried several things but I cannot get it to stop arising. As I've said it works fine, but I don't know if you have some idea as  how to bypass this error... 

thank you very much

**Comment by troyanskiy** [comment]
You can create your own method instead of overriding query
Something like that:
```typescript
@Injectable()
@ResourceParams({
  url: 'https://domain.net/api/users'
})
export class NewsRes extends ResourceCRUD<UQueryInput, CShort, Cliente> {

  @ResourceAction({
    isArray: true,
    responseInterceptor: (observable: Observable<Response>, request?: Request): Observable<any> => {
      return observable.map(res => res.json().results);
    }
  })
  queryList: ResourceMethod<UQueryInput, IData>;

}
```

**Comment by gasparherrera** [comment]
Of course ! now it works fine, thank you very much

**Comment by miguelbalboa** [comment]
Hello, @troyanskiy 
In your example, in order to map a json with the extructure:

```json
  {
    "results": [
      {...},
      {...},
    ],
    "next": "/?page=2",
    "prev": null,
    "count": 2

  }
```

you recommend to not use a array (``isArray: false)`` an use:
 
```js


export interface IData {
  results: any[];
  next: string;
  prev: string;
  count: number;
}
```

I was wondering how can we get the objects inside the ``results`` array to be mapped as ``Resources`` in orden to do:

```js
    this.newsList = this.newsRes.query({page: 1, perPage: 20});
    let firstNews = this.newsList.results[0]
    firstNews.title = 'Changed title'
    firstNews.$save()
```


This is a great Module, thanks.

**Comment by troyanskiy** [comment]
@miguelbalboa Hello.
The statement `this.newsList = this.newsRes.query({page: 1, perPage: 20});` is async, so you need to wait data to be received.
In that case you should do:
``` typescript
  this.newsList = this.newsRes.query({page: 1, perPage: 20});
  this.newsList.$observable.toPromise()
    .then(() => {
      let firstNews = this.newsList.results[0];
      firstNews.title = 'Changed title'
      // firstNews.$save(); // that will not work
      return this.newsRes.save(firstNews).$observable.toPromise();
    })
    .then((savedNews: any) => {
      // news is saved and save news received in savedNews variable
    });
```

**Comment by miguelbalboa** [comment]
Thanks @troyanskiy ,

I mean, There is any way to keep the pagination data and map the objects inside ``results`` as resources?
It would be useful as example for the JSON returned from [Laravel paginator](https://laravel.com/docs/5.3/pagination#converting-results-to-json) or Django REST as @gasparherrera exposes, and the integration with ng-bootstrap pagination or similars.

Example

```JS

this.newsRes.query({page: 1, perPage: 20}).$observable.subscribe((response) => {
    this.paginator = response;
});
```
And in the template:

```HTML
<ul>
    <li *ngFor="let item of paginator.results">
        <input type="text" [(ngModel)]="item.title">
        <!-- Using $save because item is already a resource  -->
        <a (click)="item.$save()"></>
    <li>
</ul>

<!-- ng-bootstrap component -->
<ngb-pagination [collectionSize]="paginator.total" [(page)]="paginator.current_page"></ngb-pagination>

```

Thanks for your help.
