### ISSUE TITLE
Can't resolve all parameters for CustomResource

### ISSUE THREAD

**Issue by dbettini** [troyanskiy/ng2-resource-rest#65]
I'm getting "Can't resolve all parameters for CustomResource: (?, ?)." while bootstrapping the application. The only solution for now is setting an explicit constructor in CustomResource and calling base class: 
```
@Injectable()
@ResourceParams({
    url: config.apiUrl
})
export class CustomResource extends Resource {
    constructor(http: Http, injector: Injector) {
        super(http, injector);
    }
    @ResourceAction({
        isArray: true
    })
    query: ResourceMethod<any, any[]>;
}
```
Any ideas? Versions of angular packages 2.3.0

**Comment by dbettini** [comment]
Solved, my mistake was providing the service myself instead of letting the library do it. For anyone that bumps into it, don't put your resources in the providers array.

**Comment by dmitri-wm** [comment]
@dbettini Thanks a lot. I've overgoogled 10 pages :) you saved my night
