### ISSUE TITLE
Angular-cli ahead of time (--aot) compiled-version addTimestamp exception

### ISSUE THREAD

**Issue by blaind** [troyanskiy/ng2-resource-rest#67]
When compiling angular-cli project in aot-mode, the following error is thrown:

```
EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'addTimestamp' of null
```

Failure occurs at https://github.com/troyanskiy/ng2-resource-rest/blob/8f278e028cbc7dec67ebeccedbb155ea25b4648b/src/ResourceAction.ts#L240 because resourceOptions is null. 

One possible fix is to add one-liner here https://github.com/troyanskiy/ng2-resource-rest/blob/8f278e028cbc7dec67ebeccedbb155ea25b4648b/src/ResourceAction.ts#L27 after that line:

```
if (!resourceOptions) resourceOptions = {};
```

but there might be some deeper error caused by aot compilation? E.g. why ResourceParams are not returned in AOT compilation mode?

This is how I'm using the code:

```
@Injectable()
@ResourceParams({
    params: { _angularjs: true }   
})
export class RestTable <TQuery, TShort, TFull> extends ResourceCRUD<TQuery, TShort, TFull> {
    constructor(tableName: string, http: Http, injector: Injector) {
        super(http, injector);
        this.setPath(getApiUrl('rest/' + tableName));
    }   
}

@Injectable()
export class RestService {
    constructor(private http: Http, private injector: Injector) {
    }   

    get location() {
        return new RestTable<any, Location, any>('location', this.http, this.injector);
    }   
}
```

**Comment by troyanskiy** [comment]
Hi!
I did not implement yet good support of AOT.
`ResourceParams` does not return list of resources because they where not added yet to to list (Resources files was not opened (executed) yet).

And I still did not have time to do experiments on that.

I think there was one familiar issue [here](https://github.com/troyanskiy/ng2-resource-rest/issues/62)

**Comment by blaind** [comment]
Ok, thank you! Do you have plans to support AOT sometime?

**Comment by troyanskiy** [comment]
I think it will work (I did not test) if you will do following:
1. Add `constructor`s to all your resources
2. In `ResourceParams` add `add2Provides: false`
3. Add your resources into provides list of you angular module

Please, let me know about that test.

**Comment by troyanskiy** [comment]
Closing the issue. Feel free to reopen.
