### ISSUE TITLE
Cannot convert undefined or null to object at hasOwnProperty (<anonymous>) - Ionic 2

### ISSUE THREAD

**Issue by 90lucasgabriel** [troyanskiy/ng2-resource-rest#68]
I'm trying to use the library with Ionic 2, but show this error when add  `providers: [MyResource]` or `constructor(private myRes: MyResource)`:
```
Cannot convert undefined or null to object at hasOwnProperty (<anonymous>)
```
main.js:60
```
__webpack_require__.o = function(object, property) { return Object.prototype.hasOwnProperty.call(object, property); };
```

**Comment by ducminhquan** [comment]
Me too.
Try to find out whether **ionic2** or **ng2-resource-rest** causes this.

![image](https://cloud.githubusercontent.com/assets/8302236/21375393/c80a7b02-c75f-11e6-9f3e-35ad329c35f4.png)

**Comment by ducminhquan** [comment]
It seems not compatible with `webpack@2.1.0-beta.28` (and above).

Workaround: Downgrade to `webpack@2.1.0-beta.27` and it's works.

**Comment by troyanskiy** [comment]
Hi!
Cool! They released RC4 :)
Thank you for the issue. I will check that ASAP.

**Comment by troyanskiy** [comment]
Finally, I found the reason! Please update to 1.7.0
Problem was related to WebPack which is doing the importation in wrong order.

Was related to imports in ng2-resource-rest (index) file.
Before:
```typescript
export * from './src/Interfaces';
export * from './src/Resource';
export * from './src/ResourceAction';
export * from './src/ResourceCRUD';
export * from './src/ResourceCRUDBase';
export * from './src/ResourceGlobalConfig';
export * from './src/ResourceModel';
export * from './src/ResourceParams';
export * from './src/ResourceProviders';
```

After:
```typescript
export * from './src/Resource';
export * from './src/ResourceAction';
export * from './src/ResourceCRUD';
export * from './src/ResourceCRUDBase';
export * from './src/ResourceGlobalConfig';
export * from './src/ResourceModel';
export * from './src/ResourceParams';
export * from './src/ResourceProviders';
export * from './src/Interfaces';
```
