### ISSUE TITLE
It doesn't work with webpack 1.x

### ISSUE THREAD

**Issue by girokon** [troyanskiy/ng2-resource-rest#70]
I updated to latest version, and got the error: "Uncaught SyntaxError: Unexpected token import" in ng2-resource-rest/index.js. As I see, my webpack takes `ng2-resource-rest/index.js` instead of `ng2-resource-rest/bundles/index.js`. I added alias to my webpack config for fix this: 

```
alias: {
            "ng2-resource-rest": helpers.root('node_modules/ng2-resource-rest/bundles/index.js')
        }
```

I think mistake in your package.json:

```
"main": "bundles/ng2-resource-rest.js",
```

this file doesn't exist, but there is `bundles/ng2-resource-rest.umd.js`

**Comment by troyanskiy** [comment]
Thanks a lot for the issue and sorry for long fix.
