### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined at Function.ResourceProviders.add

### ISSUE THREAD

**Issue by smnbbrv** [troyanskiy/ng2-resource-rest#73]
Happens at (build output)

```js
var deps = Reflect.getMetadata('design:paramtypes', resource);
if (deps.length === 0) {
  deps = [__WEBPACK_IMPORTED_MODULE_1__angular_http__["Http"], __WEBPACK_IMPORTED_MODULE_0__angular_core__["Injector"]];
}
```

If I add a simple `!deps` to the if condition it works fine.

Cannot get to the reason why deps could be `undefined` or an empty array, maybe it's about the injection order...

**Comment by troyanskiy** [comment]
Thank you!
New version has been published.

**Comment by smnbbrv** [comment]
as always so fast 👍  thank you very much!
