### ISSUE TITLE
setting resourcemethod parameter for body

### ISSUE THREAD

**Issue by jaideepdas** [troyanskiy/ng2-resource-rest#76]
This is the custom resource method I have added. I am passing the worksheet param which is a object expecting it to be passed as body of the request but its being passed against a key name 'worksheet' in the body.
How do I make the worksheet param as body of the request.
```
    @ResourceAction({
        method: RequestMethod.Put,
        isArray: false,
        path: '/{!:warriorId}/worksheet/{!:qstnSet}/{!:startDate}'
    })
    updateWorksheet: ResourceMethod<{ warriorId: number, startDate: number, qstnSet: string, worksheet: IWorksheet }, IWorksheet>;
```
Don't very clear from the documentation.

**Comment by troyanskiy** [comment]
Hello. For now it's not possible to do that.
I will think about the solution.

**Comment by troyanskiy** [comment]
I've made something special for you.
Please update the lib to ver 1.9.0
Now it's possible to create methods with split path params and body. In your case you can use it like that:
``` typescript
@ResourceAction({
  method: RequestMethod.Put,
  //isArray: false, by default it's false
  path: '/{!:warriorId}/worksheet/{!:qstnSet}/{!:startDate}'
})
updateWorksheet: ResourceMethodStrict<IWorksheet, { warriorId: number, startDate: number, qstnSet: string}, IWorksheet>;
```

**Comment by jaideepdas** [comment]
@troyanskiy thanks for this exactly what I was looking for. Much cleaner and legible.
