### ISSUE TITLE
how to get current request url

### ISSUE THREAD

**Issue by iloveyo123u1** [troyanskiy/ng2-resource-rest#8]
hi dear troyanskiy;

i hope  i can  use  **this.userRes.geCurrentUrl()**  get current request url
-------------------------------------------------------------------------------
i hope i can get url parameters,like this:

```
let url = "http://restframework.herokuapp.com/snippets/?page=3";

let page=getUrlPar(url,"page");
console.log(page) ; // print 3

getUrlPar(local_url,par){
        local_url = (local_url==null)?"":local_url
        let get = local_url.indexOf(par+"=");
        if (get == -1){
            return 1;
        };
        let get_par = local_url.slice(par.length+get+1);
        let nextPar = get_par.indexOf("&");
        if (nextPar != -1){
            get_par = get_par.slice(0,nextPar);
        };
        return get_par;
    }
```

-------------------------------------------------------------------------------

request url  like:

http://restframework.herokuapp.com/snippets/?page=3

i need display current page 3 in my website page

server restful  i use http://www.django-rest-framework.org/ 

servers return json  like this   http://restframework.herokuapp.com/snippets/?page=3

i need get url parameters  **page=3** ,

**Comment by iloveyo123u1** [comment]
Can you write a way to deal with the pagination？
next page and previous page

**Comment by troyanskiy** [comment]
You need to add parameter page
`this.userRes.query({page:3})`
And you need to intercept response, map to json and map again to return an array.
