### ISSUE TITLE
null getting stringified as a query parameter

### ISSUE THREAD

**Issue by dbettini** [troyanskiy/ng2-resource-rest#80]
At the moment, if you pass null as an optional parameter to a ResourceMethod, it will get sent as 'null' to the server, instead of not appending it at all, which is the case with undefined. It's also the way [URLSearchParams](https://angular.io/docs/js/latest/api/http/index/URLSearchParams-class.html#!#append-anchor) work - if you try appending headers with null or undefined value, nothing happens.

The problem is [this](https://github.com/troyanskiy/ng2-resource-rest/blob/master/src/ResourceAction.ts#L244) condition, where undefined doesn't pass but null does, and therefore gets stringified. However, stringifying in general is not needed I think, so [this](https://github.com/troyanskiy/ng2-resource-rest/blob/master/src/ResourceAction.ts#L249) line can be removed entirely, since [append](https://angular.io/docs/js/latest/api/http/index/URLSearchParams-class.html#!#append-anchor) does it anyway (I guess it's a leftover from when that wasn't the case or something).

I can make a PR if it's fine by you.

**Comment by troyanskiy** [comment]
Thanks for the Issue.
Indeed `null` is `object`
I will fix that now.
Thanks

**Comment by dbettini** [comment]
@troyanskiy this is happening again. 1.14.0 and 2.0.4.

**Comment by troyanskiy** [comment]
@dbettini Thank you for your notice.
That is fixed now with version 2.0.3

**Comment by troyanskiy** [comment]
Please note that library migrated from ng2-resource-rest to ngx-resource

**Comment by troyanskiy** [comment]
bumped version to 2.0.5
