### ISSUE TITLE
Object returned by REST client instead of wanted type

### ISSUE THREAD

**Issue by Pepek91** [troyanskiy/ng2-resource-rest#82]
Hi,

lets say I have something like this
```typescript
export class Car {
  id?: number;
  brand?: string;
  model?: string;
  engine?: Engine;
  
  getFullName(): string {
    return this.brand + ' ' + this.model;
  }
}
```

unfortunately when I get cars from my DB with ng2-resource-rest I get object with right properties of type of Object, so it is not a Car object. As consequence function `getFullName()` is unavailable. Using classes like `Engine` makes something like `Object.assign(car, object)` useless, as engine is still going to be of type Object. The only solution is to make manual constructors and use them to change each object separately before using it. Is it a bug or just intended behaviour for performance purposes?

Here is how I get cars:
```typescript
@Injectable()
@ResourceParams({
  url: 'my url'
})
export class CarRes extends ResourceCRUD<CarQuery, Car, Car> {}
```

Thanks

**Comment by troyanskiy** [comment]
Hi,
I had the same case.
You can override map method of the resource or define map for each of them separately.

```typescript
export class Car {
  id?: number;
  brand?: string;
  model?: string;
  engine?: Engine;

  constructor(data: any = null) {
    if (data) {
      this.setFromJSON(data);
    }
  }

  setFromJSON(data: any) {
    Object.assign(this, data);
    if (data.engine) {
      this.engine = new Engine(data.engine);
    }
  }

  getFullName(): string {
    return this.brand + ' ' + this.model;
  }
}
```

And in the resource
```typescript

@Injectable()
@ResourceParams({
  url: 'my url'
  // OR here
  map: (item: any) => new Car(item)
})
export class CarRes extends ResourceCRUD<CarQuery, Car, Car> {
  // OR Here
  map(item: any): Car {
    return new Car(item);
  }
}

```

**Comment by Pepek91** [comment]
Thanks for answer. Thats better then remembering to map each and every object that came from DB, but you still need to maintenance map function while adding new fields. I hoped there is some kind of smart cast option in typescript but it looks like there isn't.
