### ISSUE TITLE
 this.userRes.get()  send two request

### ISSUE THREAD

**Issue by iloveyo123u1** [troyanskiy/ng2-resource-rest#9]
```
 this.userRes.get({firstName: 'John'})
                .$observable
                .subscribe(
                    res => console.log(res),
                    err => console.log('Err', err)
                );
```

get,query,save,update,remove

could you fix it ,Let it just send a request ?

**Comment by troyanskiy** [comment]
Could you please provide me you userRes class?
Normally if you have latest version of the module the request will be sent immediately now after calling that `this.userRes.get({firstName: 'John'})`. The call will not be executed without `subscribe` only if you define that the method is kind of lazy mode (`isLazy: true`).

**Comment by iloveyo123u1** [comment]
```
import {Resource, ResourceParams, ResourceAction, ResourceResult} from "ng2-resource-rest";

import {Injectable} from "angular2/core";

import { Cookie } from 'ng2-cookies/ng2-cookies';
let csrftoken = Cookie.getCookie('csrftoken');

// Make it Injectable
@Injectable()
// Decorate the your resource class
@ResourceParams({
    // Url to api
    url: '',
    headers:{
        "X-CSRFToken":csrftoken,
        'Accept': 'application/json',
        'Content-Type': 'application/json'
    },
    // Api path
    path: '/users/{id}'
})
export class UsersRes extends Resource {}
```

**Comment by iloveyo123u1** [comment]
ng2-resource-rest
  "version": "0.2.5"

**Comment by iloveyo123u1** [comment]
If I use this line of code, it's normal.
`this.userRes.get({firstName: 'John'});`

If I use this line of code,it send two request
 ```
this.userRes.get({firstName: 'John'})
                .$observable
                .subscribe(
                    res => console.log(res),
                    err => console.log('Err', err)
                );
```

**Comment by troyanskiy** [comment]
Thank you.
I will check that.

**Comment by troyanskiy** [comment]
It fixed.
Please update the module.

**Comment by iloveyo123u1** [comment]
yes,fixed
thank you very much

i run:tsc  //compile typescript
i got a error:
`../node_modules/ng2-resource-rest/index.ts(340,21): error TS2339: Property 'connect' does not exist on type 'Observable<any>'.`

**Comment by troyanskiy** [comment]
Fixed. Please update the module

**Comment by iloveyo123u1** [comment]
thank you  very much
