### ISSUE TITLE
ng4 - Wrong path for Type 

### ISSUE THREAD

**Issue by CyrilleGuimezanes** [troyanskiy/ng2-resource-rest#90]
Hello!

I'm moving today to ng4 and at AOT compilation I get:

`Error: Error at /home/me/workspace/myapp/node_modules/ng2-resource-rest/src/Interfaces.d.ts:3:22: Cannot find module '@angular/core/src/type'.`
`Error at /home/me/workspace/myapp/node_modules/ng2-resource-rest/src/ResourceModel.d.ts:1:22: Cannot find module '@angular/core/src/type'.`
`Error at /home/me/workspace/myapp/node_modules/ng2-resource-rest/src/Resource.d.ts:3:22: Cannot find module '@angular/core/src/type'.`
`Error at /home/me/workspace/myapp/node_modules/ng2-resource-rest/src/ResourceAction.d.ts:2:22: Cannot find module '@angular/core/src/type'.`
`Error at /home/me/workspace/myapp/node_modules/ng2-resource-rest/src/ResourceParams.d.ts:1:22: Cannot find module '@angular/core/src/type'.`
`Error at /home/me/workspace/myapp/node_modules/ng2-resource-rest/src/ResourceProviders.d.ts:2:22: Cannot find module '@angular/core/src/type'.`

I think the correct path is "@angular/core" (My IDE is able to find Type on it)

I don't know if this path was changed/fixed recently...

Could you try to fix this?

Regards

**Comment by troyanskiy** [comment]
Hello. Sorry for the loooong answer.
I did not test it yet with ng4.

I will do tests on final release.

I will keep the issue open.

Thanks.

**Comment by cipchk** [comment]
+1

**Comment by troyanskiy** [comment]
Hello. Please check new version of the lib (2.0.0) and new ResourceModel
