### ISSUE TITLE
RessourceCRUD's get method issue

### ISSUE THREAD

**Issue by ChamNouki** [troyanskiy/ng2-resource-rest#92]
Hello,

I've got an issue with RessourceCRUD's get method : 

In my ressource extending RessourceCRUD i override the map method in order tu build a TypeScript object but when the observable is resolved, there is missing getter and setter in the object.

So first here is my Hero object :
```
class Hero {
  private _id: number;
  private _name: string;

  get id(): number {
    return this._id;
  }

  set id(value: number) {
    this._id = value;
  }

  setId(value: number): Hero {
    this.id = value;
    return this;
  }

  get name(): string {
    return this._name;
  }

  set name(value: string) {
    this._name = value;
  }

  setName(value: string): Hero {
    this.name = value;
    return this;
  }
}
```

and here is my ressource :

```
@Injectable()
@ResourceParams({
  url: 'api/heroes'
})
class HeroRessource extends ResourceCRUD<IQueryInput, Hero, Hero> {

  constructor($http: Http, injector: Injector) {
    super($http, injector);
  }

  // @Override
  responseInterceptor(observable: Observable<any>): Observable<any> {
    return observable.map(res => {
      return res._body ? res.json().data : null;
    });
  }

  // @Override
  map(item: any): Hero {
    return new Hero().setId(item.id).setName(item.name);
  }
}
```

the API answer with json object looks like `{ id: number, name: string }`, and my ressource map method correctly build a Hero object. BUT from my angular service when I log the result of `this.heroRessource.get({ id: +params['id'] });`, the object only contain `_id` and `_name` properties. I have to use 
```
this.heroRessource.get({ id: +params['id'] }).$observable.subscribe(hero => {});
```
to have the full object with `id` and `name` getters and setters plus `setId` and `setName` methods.

**Comment by ChamNouki** [comment]
So I've found the problème :

In RessourceAction.ts at line 328, the `Object.assign` method seems to do not assign methods or accessors.

And at line 335 you send `resp` and not `ret` as next value for subscribers.

**Comment by troyanskiy** [comment]
Hello.
For your case it will be better to use it like that
```typescript
this.heroRessource.get({ id: +params['id'] }).$observable.subscribe(hero => {
  // Here you have correct object
});
```

Or like that
```typescript
let batman: Hero = await this.heroRessource.get({ id: +params['id'] }).$observable.toPromise();
```

**Comment by ChamNouki** [comment]
Yes, those syntaxe works... but your really cool and simple syntaxe without promise or observable is just really too cool and simple to don't use it cause of basics methods or accessors ?! Can't you change the `Object.assign` method to solve the problem ?

They talk about copying accessors here :
https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Object/assign

**Comment by troyanskiy** [comment]
Please check version 1.13.0 and example on the bottom of the readme.
