### ISSUE TITLE
Unclear how to use ResourceModel

### ISSUE THREAD

**Issue by jessebuitenhuis** [troyanskiy/ng2-resource-rest#95]
Playing around with your module. I would like the $resource functionality where you can load users and each user in the list have prototype functions for $save, $remove etc.

    // Pseudo code
    this.users = UserResource.query()
    var firstUser = this.users[0];
    firstUser.$remove();

I get errors that $remove is not a function - and I tried to figure out how to get it to work - but no luck yet. 

Any pointers? Thanks!

**Comment by troyanskiy** [comment]
Hello.

Did you follow an [example on the readme file](https://github.com/troyanskiy/ng2-resource-rest#example-of-resource-model-usage)?

You need to create Resource (CRUD) and Model, then link them with each other.

**Comment by troyanskiy** [comment]
Hello.
Please check new version of the lib and new ResourceModel.

**Comment by jessebuitenhuis** [comment]
Hey, thanks for the updates! They look great, i'll check m out tonight for my project!
