### ISSUE TITLE
$resource not set on models returned from GET methods

### ISSUE THREAD

**Issue by dbettini** [troyanskiy/ng2-resource-rest#98]
At the moment, [initResultObject](https://github.com/troyanskiy/ng2-resource-rest/blob/4f2319a2e5443722eeffa7f1f0901916287ee197/src/Resource.ts#L121) is used in [ResourceAction](https://github.com/troyanskiy/ng2-resource-rest/blob/b0edb4ae8f45751ace10414acd8da453d3055c15/src/ResourceAction.ts) code to get the model, while [createModel](https://github.com/troyanskiy/ng2-resource-rest/blob/4f2319a2e5443722eeffa7f1f0901916287ee197/src/Resource.ts#L138) is the one that sets $resource on this. That results in $resource only being set when calling createModel() directly, while I'm guessing it should be called on GET ResourceAction methods as well.

**Comment by troyanskiy** [comment]
Hello.
By calling `createModel()` on GET ResourceAction will broke custom `initResultObject` function with can be provided in `ResourceAction` directive.
Did I answered on your question?

**Comment by dbettini** [comment]
I didn't really understand what you're saying... I'll try to further explain this by example.

```
@Injectable()
@ResourceParams({
    url: apiUrl + "/foo"
})
export class FooResource extends Resource {

    initResultObject(): Foo {
        return new Foo();
    }

    @ResourceAction({
        path: "/bar"
    })
    getFooBar: ResourceMethod<any, Foo>;
}
```

And then, when you try `const bar = fooService.getBar()`, `bar` does not have $resource on it. It results in [this](https://github.com/troyanskiy/ng2-resource-rest/blob/2327c69ed3dfd99571b06ead55e0c359c4fcb3ed/src/ResourceModel.ts#L63) - you're unable to call `bar.$save() `etc.

**Comment by troyanskiy** [comment]
Hello.
That is strange. The resource is set on object on [here](https://github.com/troyanskiy/ng2-resource-rest/blob/master/src/ResourceAction.ts#L79)

**Comment by dbettini** [comment]
After further investigation, I realized that those properties were deleted in my code, because of a "converting circular structure to JSON error". In other words, $resource is set correctly.

Thanks for the fast replies.
